### ISSUE TITLE
Illegal instruction - BUILD_NATIVE 

### ISSUE THREAD

**Issue by petrleocompel** [tiredofit/docker-freepbx#1]
I tried to use your container, on localhost it works pretty well, but when i try to use it on server it throwed error when you try run `/usr/sbin/asterisk` return `Illegal instruction`.
It is caused by compilation.
On my local i7 it  works but on my VPS it doesn't. 

It caused by build flags. 

Related info -> https://stackoverflow.com/questions/19607378/illegal-instruction-error-comes-when-i-start-asterisk-1-8-22/19610145#19610145

Solution should be disabling `BUILD_NATIVE` in menuselect.

**Comment by tiredofit** [comment]
Thanks for the input, I am assuming it is because it has been compiled for a specific processor type. I will make ammendments to image.

**Comment by tiredofit** [comment]
Release 0.5 disabled BUILD_NATIVE
