### ISSUE TITLE
Permission denied on /etc/amportal.conf on first start

### ISSUE THREAD

**Issue by flaviut** [tiredofit/docker-freepbx#10]
After I first start the server, I get this error when I open the http interface: `file(/etc/amportal.conf): failed to open stream: Permission denied`

This matches the permissions on the file:

```shell
root@83d4a48d1d8f:/# ls -la /etc/amportal.conf 
lrwxrwxrwx 1 asterisk asterisk 23 Apr  5 04:18 /etc/amportal.conf -> /data/etc/amportal.conf
root@83d4a48d1d8f:/# ls -la /data/etc/amportal.conf
-rw-rw---- 1 root root 19017 Apr  5 16:48 /data/etc/amportal.conf
```

As soon as I restart the server, the issue is magically fixed:

```shell
root@83d4a48d1d8f:/# ls -la /etc/amportal.conf 
lrwxrwxrwx 1 asterisk asterisk 23 Apr  5 04:18 /etc/amportal.conf -> /data/etc/amportal.conf
root@83d4a48d1d8f:/# ls -la /data/etc/amportal.conf
-rw-rw---- 1 asterisk asterisk 19017 Apr  5 16:57 /data/etc/amportal.conf
```

**Comment by tiredofit** [comment]
Thanks! I was able to track down where that went wrong. I've seen it a few times too, but quickly forgot after I restarted the container once. Docker Hub for some reason isn't letting me build. I will raise an issue with them, otherwise I will build manually and tag it as 1.22 / latest.
