### ISSUE TITLE
Proxy not forwarding to FreePBX:80

### ISSUE THREAD

**Issue by sosaucily** [tiredofit/docker-freepbx#104]
When starting the `jwilder/nginx-proxy` with the recommended command of `docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy` I get a 502 when typing my VIRTUAL_HOST url into the browser. 

In the logs for the proxy, I see the request coming through, but it gives the following error:
```
nginx.1    | 2019/10/25 10:15:18 [error] 62#62: *4 no live upstreams while connecting to upstream, client: 172.17.0.1, server: testvoip.voiptest.com, request: "GET / HTTP/1.1", upstream: "http://testvoip.voiptest.com/", host: "testvoip.voiptest.com"
```

I can access the freepbx frontend by removing the `-p 80:80` flag from the proxy start command and exposing port 80 for the freepbx app in the docker-compose file.

Any ideas? Thanks

**Comment by tiredofit** [comment]
Might want to see if you can enter the proxy container and ping the Freepbx Container. Perhaps they are on isolated networks.

**Comment by sosaucily** [comment]
Hi, thanks for the quick response. Yes, I needed to set the `networks:` key as `proxy-tier` in the proxy container as well. Now all containers are on the same network.

Sorry for the confusion, I'm still a bit new to docker. Thanks again, and thanks for releasing this awesome package!
