### ISSUE TITLE
Errors installing modules during initial setup

### ISSUE THREAD

**Issue by sosaucily** [tiredofit/docker-freepbx#107]
I've been getting a lot of what look like errors when setting up the docker for the first time. When the install is finished and I log into the FreePBX console I see a 'Module Not Found' message, and only the "Admin" tab is there. Rest are missing.

This is happening with the newest version of the docker. Any idea why?

> freepbx-app          | Downloading module 'framework'
> freepbx-app          | The following error(s) occured:
> freepbx-app          |  - Retrieved Module XML Was Empty
> freepbx-app          | No repos specified, using: [standard] from last GUI settings
> freepbx-app          | 
> freepbx-app          | Downloading module 'cdr'
> freepbx-app          | The following error(s) occured:
> freepbx-app          |  - Retrieved Module XML Was Empty
> freepbx-app          | cp: cannot stat '/var/www/html/admin/modules/cdr/install.php': No such file or directory
> freepbx-app          | sed: can't read /var/www/html/admin/modules/cdr/install.php: No such file or directory
> freepbx-app          | sed: can't read /var/www/html/admin/modules/cdr/install.php: No such file or directory
> freepbx-app          | ** [freepbx] Module Install: cdr
> freepbx-app          | Unable to install module cdr:
> freepbx-app          |  - Cannot find module
> freepbx-app          | Updating Hooks...Done
> freepbx-app          | Chowning directories...Done
> freepbx-app          | cp: cannot stat '/var/www/html/admin/modules/cdr/.install.php': No such file or directory
> freepbx-app          | ** [freepbx] Module Install: callrecordings, conferences, dashboard, featurecodeadmin, infoservices, logfiles, msuic, sipsettings, voicemail 
> freepbx-app          | No repos specified, using: [standard] from last GUI settings
> freepbx-app          | 
> freepbx-app          | Downloading module 'soundlang'
> freepbx-app          | The following error(s) occured:
> freepbx-app          |  - Retrieved Module XML Was Empty
> freepbx-app          | ** [freepbx] Module Install: certman, userman, pm2
> freepbx-app          | No repos specified, using: [standard] from last GUI settings
> freepbx-app          | 
> freepbx-app          | Downloading module 'certman'
> freepbx-app          | The following error(s) occured:
> freepbx-app          |  - Retrieved Module XML Was Empty
> freepbx-app          | Changing "SHOWLANGUAGE" from [0] to [1]
> freepbx-app          | chown: cannot access '/home/asterisk/.npm': No such file or directory
> freepbx-app          | ** [freepbx] Module Install: ucp 
> freepbx-app          | No repos specified, using: [standard] from last GUI settings

**Comment by tiredofit** [comment]
Whats your working environment? Docker on Linux? Windows? 
I really think I'm going to have to start building in a way to cache some of the install going forward to avoid some of the download and timing errors we are seeing as of late. FreePBX is constantly under development and some of their changes are notorious for breaking the image. A cat and mouse game for sure. 

Can you see what happens when you go into the container and execute - `upgrade-cdr` and check to see if the module appears, otherwise try `upgrade-core` to see if it will restore your package repository?

**Comment by sosaucily** [comment]
I'm on Mac, and yeah i'll try that right when this install finishes!

**Comment by sosaucily** [comment]
Ran the `upgrade-cdr` command and got the following:

> root@f42809e917bb:/# upgrade-cdr
> ** [freepbx] Performing Manual Upgrade of CDR Module
> cp: cannot stat '/var/www/html/admin/modules/cdr/install.php': No such file or directory
> sed: can't read /var/www/html/admin/modules/cdr/install.php: No such file or directory
> sed: can't read /var/www/html/admin/modules/cdr/install.php: No such file or directory
> No repos specified, using: [standard] from last GUI settings
> 
> cdr is not a locally installed module, unable to upgrade
> Updating Hooks...Done
> Chowning directories...Done
> cp: cannot stat '/var/www/html/admin/modules/cdr/.install.php': No such file or directory
> Taking too long? Customize the chown command, See http://wiki.freepbx.org/display/FOP/FreePBX+Chown+Conf
> Setting Permissions...
> Setting base permissions...Done
> Setting specific permissions...
>   126 [============================]
> Finished setting permissions
> {"message":"Reload Started"}
> {"message":"Reload Complete"}

`upgrade-core` returns the following:

> root@f42809e917bb:/# upgrade-core
> No repos specified, using: [standard] from last GUI settings
> 
> framework does not exist online, unable to upgrade
> Updating Hooks...Done
> Chowning directories...Done
> No repos specified, using: [standard] from last GUI settings
> 
> core is not a locally installed module, unable to upgrade
> Updating Hooks...Done
> Chowning directories...Done
> Taking too long? Customize the chown command, See http://wiki.freepbx.org/display/FOP/FreePBX+Chown+Conf
> Setting Permissions...
> Setting base permissions...Done
> Setting specific permissions...
>   129 [============================]
> Finished setting permissions
> {"message":"Reload Started"}
> {"message":"Reload Complete"}

I also tried `fwconsole ma downloadinstall core` which returns:

> root@f42809e917bb:/# fwconsole ma downloadinstall core   
> No repos specified, using: [standard] from last GUI settings
> 
> Downloading module 'core'
> The following error(s) occured:
>  - Retrieved Module XML Was Empty
> 

My docker box definitely has internet access, as it's able to wget from the internet. Seems like the package system ain't quite right tonight!
----

Perhaps unrelated, i'm also seeing some strange DB related errors on startup:

> [ERROR] mysqld: Table './mysql/user' is marked as crashed and should be repaired
> freepbx-db           | 2019-10-31  8:56:55 0 [Warning] Checking table:   './mysql/user'
> freepbx-db           | 2019-10-31  8:56:55 0 [ERROR] mysql.user: 1 client is using or hasn't closed the table properly
> freepbx-db           | 2019-10-31  8:56:55 0 [ERROR] mysqld: Table './mysql/db' is marked as crashed and should be repaired
> freepbx-db           | 2019-10-31  8:56:55 0 [Warning] Checking table:   './mysql/db'
> freepbx-db           | 2019-10-31  8:56:55 0 [ERROR] mysql.db: 1 client is using or hasn't closed the table properly

**Comment by sosaucily** [comment]
tried running `fwconsole ma listonline` and got this:

> No repos specified, using: [standard] from last GUI settings
> 
> +-----------+------------+-------------------------------+---------+
> | Module    | Version    | Status                        | License |
> +-----------+------------+-------------------------------+---------+
> | builtin   |            | Enabled; Not available online |         |
> | framework | 15.0.16.21 | Enabled; Not available online | GPLv2+  |
> +-----------+------------+-------------------------------+---------+
> msmtp: cannot locate host postfix-relay: Name or service not known
> msmtp: could not send mail (account default from /etc/msmtprc)

So it kinda seems there aren't any matching modules online.

**Comment by tiredofit** [comment]
Alright, you have a couple things going on.
`SMTP_HOST` will set your host from postfix-relay to something else (see https://www.github.com/tiredofit/docker-debian) for those mail variables.

I think there's something broken with the FreePBX package repository at this point in time, Let's give it a day and see if it comes back online. I (In Canada) am not seeing the issues on my side but am not sure if they have some sort of content delivery network issue or not.
I also can boot into a Mac installation on this PC so I will give it a go on my mac install to see if I get the same results.

**Comment by sosaucily** [comment]
Yep, FreePBX module server was down, or at least the local CDN / route. I'm here in central europe. I didn't know that was a thing that might happen :) Thanks for the help

**Comment by tiredofit** [comment]
Right on! Glad it's working again. 
I never did respond re your MySQL issue. Is that the internal SQL server or are you using an external one? I've had best success with the external one. But if you keep having those issues regardless should be an easy fix if you already have a working install to get into the SQL command line and run a repair of the tables to clear any flags it may have attached. 

I know we have seen some weird issues with Mysql on Windows, I don't think Docker on Mac would have the same issues.

**Comment by sosaucily** [comment]
I am using your sample docker-compose file, so I'm using the included external mariadb. Now that the FreePBX system is reachable I reinstalled and everything seems great. Thanks again!
