### ISSUE TITLE
update mariadb-connector-odbc version

### ISSUE THREAD

**Issue by lfarkas** [tiredofit/docker-freepbx#111]
it'd be nice to update mariadb-connector-odbc version to 3.1.5. at the same time it's be the best to make it a parameter in dockerfiles same as the BCG729_VERSION and SPANDSP_VERSION.

**Comment by tiredofit** [comment]
Sadly 3.x does not work properly with Freepbx under Debian, and more trouble than it is worth to maintain when it falls apart. Once they move to FreePBX 16 with more modernized codebase I will do so.
