### ISSUE TITLE
Reloading message doesn't dissappear 

### ISSUE THREAD

**Issue by nailsaitov** [tiredofit/docker-freepbx#115]
Using FreePBX 15, when pressing "Apply Config" a reloading message appears on the screen and stuck untill reloading the page. Config seems applying, but this issue is irratating, every time reloading the page is not a solution. Please, help!
![image](https://user-images.githubusercontent.com/43238418/71057210-1c28ed80-2186-11ea-9bfe-282caa23d8e9.png)

**Comment by guswct** [comment]
same here

**Comment by mancix** [comment]
It seems related to this one https://issues.freepbx.org/browse/FREEPBX-20698

**Comment by hakancunier** [comment]
my problem is 
Unknown Error. Please Run: fwconsole reload --verbose

**Comment by tiredofit** [comment]
Resolved with `tiredofit/freepbx:15-4.0.0`

**Comment by zombielinux** [comment]
This issue has re-emerged with the latest pull.
