### ISSUE TITLE
New freepbx breaks database?

### ISSUE THREAD

**Issue by barhom** [tiredofit/docker-freepbx#121]
Hey,

Since you are always pulling freepbx 15 "latest" then you can get breaking changes.
For example look here:

https://github.com/FreePBX/framework/commit/0c0e06024cd68afa29917ffab10356d8686a9293#diff-bd921dd8daacb5ab58836d3f2822f593

You see that they changed from 'localhost' to '$answers['dbhost']'.
Therefore your script that does,

sed -i -e 's/$amp_conf\['\''AMPDBHOST'\''\] = '\''localhost'\'';/$amp_conf\['\''AMPDBHOST'\''\] = '\''db.XXX.se'\'';/g' /usr/src/freepbx/installlib/installcommand.class.php

fails

**Comment by tiredofit** [comment]
Thanks for noticing this. Seems they are finally upgrading their code base which is great and alot of my hacks that have been in place for a few years can finally go away. A new build it happening and tagged `15-3.9.3` or `15-latest`.
