### ISSUE TITLE
cant enable modules (IVR,RingGroups,TimeConditions)

### ISSUE THREAD

**Issue by hakancunier** [tiredofit/docker-freepbx#122]
Hi,

Im installing modules like Ring Groups, IVR and more. But nothing shown in Application menu?

What am i doing wrong?

**Comment by Ragenose** [comment]
I think this is related to this #119 
I had the same issue that Ring Groups doesn't show up. I tried to go into the shell of the container and using this command to install the module.
```bash
fwconsole ma install ringgroups
```
Then, refresh the page and it works.
Hope this will help

**Comment by tiredofit** [comment]
Problem seems to have been resolved with latest Freepbx Upstream release. Cannot Recreate on new `tiredofit/freepbx:15-4.0.0` release.
