### ISSUE TITLE
What is the default user and password to login in Control Panel?

### ISSUE THREAD

**Issue by cristotodev** [tiredofit/docker-freepbx#123]
I used your docker-compose.yml example to build the containers but I can't login into "User Control Panel".
I connected on mysql container and change the value into "ampusers" table but not working.

**Comment by tiredofit** [comment]
You'll need to setup Users first via the admin panel and allow them access to the UCP. Try going in through the /admin endpoint first before heading to UCP. I made UCP come up by default (which is configurable via an environment variable) for the users of UCP benefit.

**Comment by cristotodev** [comment]
Thank you!
I can access!! :)

**Comment by kjohn1972** [comment]
Hi sir.why not frankly give out ucp password(even ciphered in .conf)? Setting up freepbx is just 1 minor part of my test work ,killing time to hack or short the password make no sense of it.pls send the username/pass to kjohn1972@hotmail.com ,thanks.

**Comment by kjohn1972** [comment]
Hi sir.why not frankly give out ucp username/password(even ciphered in .conf)? Setting up freepbx is just 1 minor part of my test work ,killing time to hack or short the password make no sense of it.pls send the user/pass to kjohn1972@hotmail.com ,thanks.
