### ISSUE TITLE
Unable to build latest version

### ISSUE THREAD

**Issue by treed593** [tiredofit/docker-freepbx#127]
Based on Commit 950b3a4

Step 3/10 : ENV ASTERISK_VERSION=17.2.0     FREEPBX_VERSION=15.0.16.45     MARIAODBC_VERSION=2.0.19     BCG729_VERSION=1.0.4     SPANDSP_VERSION=20180108     DB_EMBEDDED=TRUE     UCP_FIRST=TRUE
 ---> Using cache
 ---> 7bc0e39537bf
Step 4/10 : RUN echo "Package: libxml2*" > /etc/apt/preferences.d/libxml2 &&     echo "Pin: release o=Debian,n=buster" >> /etc/apt/preferences.d/libxml2 &&     echo "Pin-Priority: 501" >> /etc/apt/preferences.d/libxml2
 ---> Using cache
 ---> 7aae756ddb12
Step 5/10 : RUN set -x &&     curl https://packages.sury.org/php/apt.gpg | apt-key add - &&     echo "deb https://packages.sury.org/php/ buster main" > /etc/apt/sources.list.d/deb.sury.org.list &&     curl https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add - &&     echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main" > /etc/apt/sources.list.d/mongodb-org.list &&     apt-get update  &&     apt-get -o Dpkg::Options::="--force-confold" upgrade -y &&             ASTERISK_BUILD_DEPS='                        autoconf                         automake                         bison                         build-essential                         doxygen                         flex                         libasound2-dev                         libcurl4-openssl-dev                         libedit-dev                         libical-dev                         libiksemel-dev                         libjansson-dev                         libmariadbclient-dev                         libncurses5-dev                         libneon27-dev                         libnewt-dev                         libogg-dev                         libresample1-dev                         libspandsp-dev                         libsqlite3-dev                         libsrtp2-dev                         libssl-dev                         libtiff-dev                         libtool-bin                         libvorbis-dev                         libxml2-dev                         linux-headers-amd64                         python-dev                         subversion                         unixodbc-dev                         uuid-dev                         ' &&         apt-get install --no-install-recommends -y                     $ASTERISK_BUILD_DEPS                     apache2                     composer                     fail2ban                     flite                     ffmpeg                     git                     g++                     iptables                     lame                     libiodbc2                     libicu63                     libicu-dev                     libsrtp2-1                     locales                     locales-all                     mariadb-client                     mariadb-server                     mongodb-org                     mpg123                     php5.6                     php5.6-cli                     php5.6-curl                     php5.6-gd                     php5.6-ldap                     php5.6-mbstring                     php5.6-mysql                     php5.6-sqlite                     php5.6-xml                     php5.6-zip                     php5.6-intl                     php-pear                     pkg-config                     sox                     sqlite3                     unixodbc                     uuid                     wget                     whois                     xmlstarlet                     &&         cd /usr/src &&     mkdir -p mariadb-connector &&     curl -sSL  https://downloads.mariadb.com/Connectors/odbc/connector-odbc-${MARIAODBC_VERSION}/mariadb-connector-odbc-${MARIAODBC_VERSION}-ga-debian-x86_64.tar.gz | tar xvfz - -C /usr/src/mariadb-connector &&     cp mariadb-connector/lib/libmaodbc.so /usr/lib/x86_64-linux-gnu/odbc/ &&         addgroup --gid 2600 asterisk &&     adduser --uid 2600 --gid 2600 --gecos "Asterisk User" --disabled-password asterisk &&         mkdir -p /usr/src/spandsp &&     curl -kL http://sources.buildroot.net/spandsp/spandsp-${SPANDSP_VERSION}.tar.gz | tar xvfz - --strip 1 -C /usr/src/spandsp &&     cd /usr/src/spandsp &&     ./configure &&     make &&     make install &&         cd /usr/src &&     mkdir -p asterisk &&     curl -sSL http://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-${ASTERISK_VERSION}.tar.gz | tar xvfz - --strip 1 -C /usr/src/asterisk &&     cd /usr/src/asterisk/ &&     make distclean &&     contrib/scripts/get_mp3_source.sh &&     ./configure --with-resample --with-pjproject-bundled --with-jansson-bundled --with-ssl=ssl --with-srtp &&     make menuselect/menuselect menuselect-tree menuselect.makeopts &&     menuselect/menuselect --disable BUILD_NATIVE                           --enable app_confbridge                           --enable app_fax                           --enable app_macro                           --enable codec_opus                           --enable codec_silk                           --enable format_mp3                           --enable BETTER_BACKTRACES                           --disable MOH-OPSOUND-WAV                           --enable MOH-OPSOUND-GSM     make &&     make install &&     make install-headers &&     make config &&     ldconfig &&         git clone https://github.com/BelledonneCommunications/bcg729 /usr/src/bcg729 &&     cd /usr/src/bcg729 &&     git checkout tags/$BCG729_VERSION &&     ./autogen.sh &&     ./configure --libdir=/lib &&     make &&     make install &&         mkdir -p /usr/src/asterisk-g72x &&     curl https://bitbucket.org/arkadi/asterisk-g72x/get/master.tar.gz | tar xvfz - --strip 1 -C /usr/src/asterisk-g72x &&     cd /usr/src/asterisk-g72x &&     ./autogen.sh &&     ./configure --with-bcg729 --enable-penryn &&     make &&     make install &&         mkdir -p /var/run/fail2ban &&     cd / &&     rm -rf /usr/src/* /tmp/* /etc/cron* &&     apt-get purge -y $ASTERISK_BUILD_DEPS libspandsp-dev &&     apt-get -y autoremove &&     apt-get clean &&     apt-get install -y make &&     rm -rf /var/lib/apt/lists/* &&         sed -i -e "s/memory_limit = 128M/memory_limit = 256M/g" /etc/php/5.6/apache2/php.ini &&     sed -i 's/\(^upload_max_filesize = \).*/\120M/' /etc/php/5.6/apache2/php.ini &&     a2disconf other-vhosts-access-log.conf &&     a2enmod rewrite &&     a2enmod headers &&     rm -rf /var/log/* &&     mkdir -p /var/log/asterisk &&     mkdir -p /var/log/apache2 &&     mkdir -p /var/log/httpd &&         echo '%zabbix ALL=(asterisk) NOPASSWD:/usr/sbin/asterisk' >> /etc/sudoers &&         mkdir -p /assets/config/var/lib/ /assets/config/home/ &&     mv /home/asterisk /assets/config/home/ &&     ln -s /data/home/asterisk /home/asterisk &&     mv /var/lib/asterisk /assets/config/var/lib/ &&     ln -s /data/var/lib/asterisk /var/lib/asterisk &&     ln -s /data/usr/local/fop2 /usr/local/fop2 &&     mkdir -p /assets/config/var/run/ &&     mv /var/run/asterisk /assets/config/var/run/ &&     mv /var/lib/mysql /assets/config/var/lib/ &&     mkdir -p /assets/config/var/spool &&     mv /var/spool/cron /assets/config/var/spool/ &&     ln -s /data/var/spool/cron /var/spool/cron &&     mkdir -p /var/run/mongodb &&     rm -rf /var/lib/mongodb &&     ln -s /data/var/lib/mongodb /var/lib/mongodb &&     ln -s /data/var/run/asterisk /var/run/asterisk &&     rm -rf /var/spool/asterisk &&     ln -s /data/var/spool/asterisk /var/spool/asterisk &&     rm -rf /etc/asterisk &&     ln -s /data/etc/asterisk /etc/asterisk
 ---> Running in 205d20b56738
+ apt-key add -
+ curl https://packages.sury.org/php/apt.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key output should not be parsed (stdout is not a terminal)
100  1769  100  1769    0     0  12395      0 --:--:-- --:--:-- --:--:-- 12457
OK
+ echo deb https://packages.sury.org/php/ buster main
+ curl https://www.mongodb.org/static/pgp/server-4.2.asc
+ apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key output should not be parsed (stdout is not a terminal)
100  1691  100  1691    0     0   7469      0 --:--:-- --:--:-- --:--:--  7482
OK
+ echo deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main
+ apt-get update
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Ign:3 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 InRelease
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 https://packages.sury.org/php buster InRelease [6759 B]
Get:6 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 Release [1490 B]
Get:7 http://repo.zabbix.com/zabbix/4.4/debian stretch InRelease [7097 B]
Get:9 https://deb.nodesource.com/node_10.x stretch InRelease [4585 B]
Get:8 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:11 http://deb.debian.org/debian stretch Release.gpg [2410 B]
Get:10 http://security-cdn.debian.org stretch/updates InRelease [94.3 kB]
Get:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages [27.9 kB]
Get:13 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 Release.gpg [801 B]
Get:14 https://packages.sury.org/php buster/main amd64 Packages [132 kB]
Get:15 http://repo.zabbix.com/zabbix/4.4/debian stretch/main Sources [1213 B]
Get:16 http://repo.zabbix.com/zabbix/4.4/debian stretch/main amd64 Packages [4802 B]
Get:17 https://deb.nodesource.com/node_10.x stretch/main amd64 Packages [765 B]
Get:18 http://deb.debian.org/debian stretch/main amd64 Packages [7083 kB]
Get:19 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages [520 kB]
Get:20 http://security-cdn.debian.org stretch/updates/main Sources [209 kB]
Get:21 http://security-cdn.debian.org stretch/updates/contrib Sources [1384 B]
Get:22 http://security-cdn.debian.org stretch/updates/non-free Sources [1216 B]
Get:23 http://security-cdn.debian.org stretch/updates/main amd64 Packages [520 kB]
Get:24 http://security-cdn.debian.org stretch/updates/contrib amd64 Packages [1760 B]
Get:25 http://security-cdn.debian.org stretch/updates/non-free amd64 Packages [1596 B]
Get:26 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2/main amd64 Packages [3453 B]
Fetched 8929 kB in 2s (3373 kB/s)
Reading package lists...
+ apt-get -o Dpkg::Options::=--force-confold upgrade -y
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages have been kept back:
  libidn2-0 libssl1.1 openssl
The following packages will be upgraded:
  curl libcurl3 libcurl3-gnutls libpcre3 zabbix-agent
5 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Need to get 1620 kB of archives.
After this operation, 13.3 kB of additional disk space will be used.
Get:1 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 curl amd64 7.52.1-5+deb9u10 [227 kB]
Get:4 https://packages.sury.org/php buster/main amd64 libpcre3 amd64 2:8.43-1+0~20190710.6+debian10~1.gbpbfc49f [343 kB]
Get:2 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 libcurl3 amd64 7.52.1-5+deb9u10 [292 kB]
Get:5 http://repo.zabbix.com/zabbix/4.4/debian stretch/main amd64 zabbix-agent amd64 1:4.4.6-1+stretch [468 kB]
Get:3 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 libcurl3-gnutls amd64 7.52.1-5+deb9u10 [290 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 1620 kB in 0s (2919 kB/s)
(Reading database ... 14287 files and directories currently installed.)
Preparing to unpack .../libpcre3_2%3a8.43-1+0~20190710.6+debian10~1.gbpbfc49f_amd64.deb ...
Unpacking libpcre3:amd64 (2:8.43-1+0~20190710.6+debian10~1.gbpbfc49f) over (2:8.39-3) ...
Setting up libpcre3:amd64 (2:8.43-1+0~20190710.6+debian10~1.gbpbfc49f) ...
(Reading database ... 14287 files and directories currently installed.)
Preparing to unpack .../curl_7.52.1-5+deb9u10_amd64.deb ...
Unpacking curl (7.52.1-5+deb9u10) over (7.52.1-5+deb9u9) ...
Preparing to unpack .../libcurl3_7.52.1-5+deb9u10_amd64.deb ...
Unpacking libcurl3:amd64 (7.52.1-5+deb9u10) over (7.52.1-5+deb9u9) ...
Preparing to unpack .../libcurl3-gnutls_7.52.1-5+deb9u10_amd64.deb ...
Unpacking libcurl3-gnutls:amd64 (7.52.1-5+deb9u10) over (7.52.1-5+deb9u9) ...
Preparing to unpack .../zabbix-agent_1%3a4.4.6-1+stretch_amd64.deb ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of stop.
Unpacking zabbix-agent (1:4.4.6-1+stretch) over (1:4.4.5-2+stretch) ...
Setting up libcurl3:amd64 (7.52.1-5+deb9u10) ...
Setting up libcurl3-gnutls:amd64 (7.52.1-5+deb9u10) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up zabbix-agent (1:4.4.6-1+stretch) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up curl (7.52.1-5+deb9u10) ...
+ ASTERISK_BUILD_DEPS=                        autoconf                         automake                         bison                         build-essential                         doxygen                         flex                         libasound2-dev                         libcurl4-openssl-dev                         libedit-dev                         libical-dev                         libiksemel-dev                         libjansson-dev                         libmariadbclient-dev                         libncurses5-dev                         libneon27-dev                         libnewt-dev                         libogg-dev                         libresample1-dev                         libspandsp-dev                         libsqlite3-dev                         libsrtp2-dev                         libssl-dev                         libtiff-dev                         libtool-bin                         libvorbis-dev                         libxml2-dev                         linux-headers-amd64                         python-dev                         subversion                         unixodbc-dev                         uuid-dev
+ apt-get install --no-install-recommends -y autoconf automake bison build-essential doxygen flex libasound2-dev libcurl4-openssl-dev libedit-dev libical-dev libiksemel-dev libjansson-dev libmariadbclient-dev libncurses5-dev libneon27-dev libnewt-dev libogg-dev libresample1-dev libspandsp-dev libsqlite3-dev libsrtp2-dev libssl-dev libtiff-dev libtool-bin libvorbis-dev libxml2-dev linux-headers-amd64 python-dev subversion unixodbc-dev uuid-dev apache2 composer fail2ban flite ffmpeg git g++ iptables lame libiodbc2 libicu63 libicu-dev libsrtp2-1 locales locales-all mariadb-client mariadb-server mongodb-org mpg123 php5.6 php5.6-cli php5.6-curl php5.6-gd php5.6-ldap php5.6-mbstring php5.6-mysql php5.6-sqlite php5.6-xml php5.6-zip php5.6-intl php-pear pkg-config sox sqlite3 unixodbc uuid wget whois xmlstarlet
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apache2 : Depends: apache2-bin (= 2.4.25-3+deb9u9) but it is not going to be installed
 ffmpeg : Depends: libavdevice57 (>= 7:3.2.14) but it is not going to be installed
          Depends: libavfilter6 (>= 7:3.2.14) but it is not going to be installed or
                   libavfilter-extra6 (>= 7:3.2.14) but it is not going to be installed
          Depends: libavformat57 (>= 7:3.2.14) but it is not going to be installed
 libneon27-dev : Depends: libneon27 (= 0.30.2-2) but it is not going to be installed
 libssl-dev : Depends: libssl1.1 (= 1.1.1d-1+0~20191009.15+debian10~1.gbpd6badf) but 1.1.0l-1~deb9u1 is to be installed
 libxml2-dev : Depends: libxml2 (= 2.9.9+dfsg-1+0~20200226.5+debian10~1.gbp3b6674) but it is not going to be installed
 mongodb-org : Depends: mongodb-org-shell but it is not going to be installed
               Depends: mongodb-org-server but it is not going to be installed
               Depends: mongodb-org-mongos but it is not going to be installed
 php5.6 : Depends: libapache2-mod-php5.6 but it is not going to be installed or
                   php5.6-fpm but it is not going to be installed or
                   php5.6-cgi but it is not going to be installed
 php5.6-cli : Depends: php5.6-opcache but it is not going to be installed
              Depends: php5.6-readline but it is not going to be installed
              Depends: libc6 (>= 2.27) but 2.24-11+deb9u4 is to be installed
              Depends: libxml2 (>= 2.8.0) but it is not going to be installed
 php5.6-curl : Depends: libcurl4 (>= 7.18.0) but it is not installable
 php5.6-gd : Depends: libgd3 (>= 2.1.1) but it is not going to be installed
 php5.6-ldap : Depends: libsasl2-2 (>= 2.1.27+dfsg) but 2.1.27~101-g0780600+dfsg-3+deb9u1 is to be installed
 php5.6-xml : Depends: libxml2 (>= 2.9.0) but it is not going to be installed
              Depends: libxslt1.1 (>= 1.1.25) but it is not going to be installed
 php5.6-zip : Depends: libc6 (>= 2.27) but 2.24-11+deb9u4 is to be installed
 xmlstarlet : Depends: libxml2 (>= 2.7.4) but it is not going to be installed
              Depends: libxslt1.1 (>= 1.1.25) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c set -x &&     curl https://packages.sury.org/php/apt.gpg | apt-key add - &&     echo "deb https://packages.sury.org/php/ buster main" > /etc/apt/sources.list.d/deb.sury.org.list &&     curl https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add - &&     echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main" > /etc/apt/sources.list.d/mongodb-org.list &&     apt-get update  &&     apt-get -o Dpkg::Options::="--force-confold" upgrade -y &&             ASTERISK_BUILD_DEPS='                        autoconf                         automake                         bison                         build-essential                         doxygen                         flex                         libasound2-dev                         libcurl4-openssl-dev                         libedit-dev                         libical-dev                         libiksemel-dev                         libjansson-dev                         libmariadbclient-dev                         libncurses5-dev                         libneon27-dev                         libnewt-dev                         libogg-dev                         libresample1-dev                         libspandsp-dev                         libsqlite3-dev                         libsrtp2-dev                         libssl-dev                         libtiff-dev                         libtool-bin                         libvorbis-dev                         libxml2-dev                         linux-headers-amd64                         python-dev                         subversion                         unixodbc-dev                         uuid-dev                         ' &&         apt-get install --no-install-recommends -y                     $ASTERISK_BUILD_DEPS                     apache2                     composer                     fail2ban                     flite                     ffmpeg                     git                     g++                     iptables                     lame                     libiodbc2                     libicu63                     libicu-dev                     libsrtp2-1                     locales                     locales-all                     mariadb-client                     mariadb-server                     mongodb-org                     mpg123                     php5.6                     php5.6-cli                     php5.6-curl                     php5.6-gd                     php5.6-ldap                     php5.6-mbstring                     php5.6-mysql                     php5.6-sqlite                     php5.6-xml                     php5.6-zip                     php5.6-intl                     php-pear                     pkg-config                     sox                     sqlite3                     unixodbc                     uuid                     wget                     whois                     xmlstarlet                     &&         cd /usr/src &&     mkdir -p mariadb-connector &&     curl -sSL  https://downloads.mariadb.com/Connectors/odbc/connector-odbc-${MARIAODBC_VERSION}/mariadb-connector-odbc-${MARIAODBC_VERSION}-ga-debian-x86_64.tar.gz | tar xvfz - -C /usr/src/mariadb-connector &&     cp mariadb-connector/lib/libmaodbc.so /usr/lib/x86_64-linux-gnu/odbc/ &&         addgroup --gid 2600 asterisk &&     adduser --uid 2600 --gid 2600 --gecos "Asterisk User" --disabled-password asterisk &&         mkdir -p /usr/src/spandsp &&     curl -kL http://sources.buildroot.net/spandsp/spandsp-${SPANDSP_VERSION}.tar.gz | tar xvfz - --strip 1 -C /usr/src/spandsp &&     cd /usr/src/spandsp &&     ./configure &&     make &&     make install &&         cd /usr/src &&     mkdir -p asterisk &&     curl -sSL http://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-${ASTERISK_VERSION}.tar.gz | tar xvfz - --strip 1 -C /usr/src/asterisk &&     cd /usr/src/asterisk/ &&     make distclean &&     contrib/scripts/get_mp3_source.sh &&     ./configure --with-resample --with-pjproject-bundled --with-jansson-bundled --with-ssl=ssl --with-srtp &&     make menuselect/menuselect menuselect-tree menuselect.makeopts &&     menuselect/menuselect --disable BUILD_NATIVE                           --enable app_confbridge                           --enable app_fax                           --enable app_macro                           --enable codec_opus                           --enable codec_silk                           --enable format_mp3                           --enable BETTER_BACKTRACES                           --disable MOH-OPSOUND-WAV                           --enable MOH-OPSOUND-GSM     make &&     make install &&     make install-headers &&     make config &&     ldconfig &&         git clone https://github.com/BelledonneCommunications/bcg729 /usr/src/bcg729 &&     cd /usr/src/bcg729 &&     git checkout tags/$BCG729_VERSION &&     ./autogen.sh &&     ./configure --libdir=/lib &&     make &&     make install &&         mkdir -p /usr/src/asterisk-g72x &&     curl https://bitbucket.org/arkadi/asterisk-g72x/get/master.tar.gz | tar xvfz - --strip 1 -C /usr/src/asterisk-g72x &&     cd /usr/src/asterisk-g72x &&     ./autogen.sh &&     ./configure --with-bcg729 --enable-penryn &&     make &&     make install &&         mkdir -p /var/run/fail2ban &&     cd / &&     rm -rf /usr/src/* /tmp/* /etc/cron* &&     apt-get purge -y $ASTERISK_BUILD_DEPS libspandsp-dev &&     apt-get -y autoremove &&     apt-get clean &&     apt-get install -y make &&     rm -rf /var/lib/apt/lists/* &&         sed -i -e "s/memory_limit = 128M/memory_limit = 256M/g" /etc/php/5.6/apache2/php.ini &&     sed -i 's/\(^upload_max_filesize = \).*/\120M/' /etc/php/5.6/apache2/php.ini &&     a2disconf other-vhosts-access-log.conf &&     a2enmod rewrite &&     a2enmod headers &&     rm -rf /var/log/* &&     mkdir -p /var/log/asterisk &&     mkdir -p /var/log/apache2 &&     mkdir -p /var/log/httpd &&         echo '%zabbix ALL=(asterisk) NOPASSWD:/usr/sbin/asterisk' >> /etc/sudoers &&         mkdir -p /assets/config/var/lib/ /assets/config/home/ &&     mv /home/asterisk /assets/config/home/ &&     ln -s /data/home/asterisk /home/asterisk &&     mv /var/lib/asterisk /assets/config/var/lib/ &&     ln -s /data/var/lib/asterisk /var/lib/asterisk &&     ln -s /data/usr/local/fop2 /usr/local/fop2 &&     mkdir -p /assets/config/var/run/ &&     mv /var/run/asterisk /assets/config/var/run/ &&     mv /var/lib/mysql /assets/config/var/lib/ &&     mkdir -p /assets/config/var/spool &&     mv /var/spool/cron /assets/config/var/spool/ &&     ln -s /data/var/spool/cron /var/spool/cron &&     mkdir -p /var/run/mongodb &&     rm -rf /var/lib/mongodb &&     ln -s /data/var/lib/mongodb /var/lib/mongodb &&     ln -s /data/var/run/asterisk /var/run/asterisk &&     rm -rf /var/spool/asterisk &&     ln -s /data/var/spool/asterisk /var/spool/asterisk &&     rm -rf /etc/asterisk &&     ln -s /data/etc/asterisk /etc/asterisk' returned a non-zero code: 100

**Comment by tiredofit** [comment]
Can you make sure you have pulled the latest copy of the base image `tiredofit/nodejs:10-debian-latest`

I'm seeing references to Debian Stretch but we've moved over to Buster on this one.

**Comment by treed593** [comment]
That would do it. Thank you!
