### ISSUE TITLE
username / password - where set ?

### ISSUE THREAD

**Issue by fabianus76** [tiredofit/docker-freepbx#128]
Hello everybody, in the Quick Start section it says "Login to the web server and enter in your admin username, admin password, and email address". I can not figure out where these are set in the composer file. Or are there any default values? Thanks for any feedback !

**Comment by fabianus76** [comment]
solved - understood that I had to access the admin folder ...

**Comment by blakev** [comment]
This is a HUGE oversight in the README, I just spent 45 minutes to find this issue.

You have to visit `http://<your-ip-address>/admin/config.php` to set up the server on the first run.

**Comment by tiredofit** [comment]
README changed to: 

Login to the web server's admin URL (default /admin) and enter in your admin username, admin password, and email address and start configuring the system!

**Comment by p0358** [comment]
@tiredofit this is still confusing, it should say something like `default URL: <ip>/admin`, or at least "default path"
