### ISSUE TITLE
cannot find Firewall in the Connectivity menu (freepbx)

### ISSUE THREAD

**Issue by fabianus76** [tiredofit/docker-freepbx#130]
Hi everybody, 

I can not find the Firewall in the Connectivity menu. Is this normal for docker-freepbx? Or did I anything wrong?

**Comment by tiredofit** [comment]
I don't believe Firewall exists in this release, only in the Sangoma Distribution.

**Comment by fabianus76** [comment]
ok - thank you for the feedback !
