### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by BitCol** [tiredofit/docker-freepbx#14]
Hello, 

I would like to use your container, having some issues running it from scratch, could you please update the broken links on the documentation with the docker-compose.yml files ? and maybe a hint on how to run it manually ? 

Thanks a lot.

**Comment by tiredofit** [comment]
Hi, you should be able to find the sample docker-compose file underneath the "examples" folder of this repo. I will update the README.md however.

**Comment by BitCol** [comment]
Hint on how to run it /build it with portainer would be great . 

Thanks again. 

PS: Your freepbx continer seems to be the most up to date currently.

**Comment by tiredofit** [comment]
Definitely the most up to date! Having a bit of a problem (really, I just need time) to get Asterisk 15 bolted into it, but that will come, along with an Alpine image as well.
I have only used Portainer briefly, however it should be fairly simple to just replicate the environment variables listed in the docker-compose along with the exported volumes. Really, if you wanted to give it a whirl even on its own without any environment variables and just exposed port 80 to your system, it should work without any tweaks out of the box so you could test it out.
I'm the Director of an organization and we are in the process of deploying this as we speak so there will be a few changes as I find any potential bugs lurking with it, if I get some time to go back into Portainer I will and will advise..

**Comment by BitCol** [comment]
Awesome, I will keep track and will be testing as the updates come in. Thanks for the reply.

**Comment by BitCol** [comment]
This is my config, container running, but nothing loads on the browser using the ports. 32801 & 32802
PICS: https://imgur.com/a/fev5U

**Comment by tiredofit** [comment]
The last pane of that screenshot is interesting. It appears the volumes aren't working at all. Did you create any by chance? Knowing that portainer uses actual volumes rather than exposing to the file system (I think?) I'm wondering if you might have uncovered a bit of a bug.. 

Have you tried running though just with the sample docker-compose?

**Comment by BitCol** [comment]
That was the problem, I was not creating the volumes manually, after adding them it did work. 

Having this problem when updating modules. This last two wont upgrade. 
https://imgur.com/a/hjt6M

Thanks a bunch

**Comment by tiredofit** [comment]
System Admin is an interesting one. It's not really relevant with this container, and while at one point 2 weeks back I compiled in the PHP Zend loader, we could never get the Sysadmin Module to work. They use that to allow you to have Commercial Modules to function, but we didn't invest much time into it. I can build a copy of it with the Loader if you'd like, but wouldn't be able to do much support on that branch for a few weeks.

As for XMPP, my Sysadmin has said yes he has been able to install it, however it needs to have mongodb installed inside the container. If you wanted to build your own version and include it go for it!

**Comment by BitCol** [comment]
This works great for our development for now, can't wait for the newer version, please let me know if I can do some testing. 

Thanks, and best to you.

**Comment by BitCol** [comment]
I've configured everything as default, created two pjsip extensiones 101 and 102, enabled UCP and everything else by default. 

I can connected to the UCP with the extensions, but I can't make calls, nor I can connected with a SIP client. only using WEb UCP

Any idea ?

**Comment by tiredofit** [comment]
Lots of trial and error! Make sure you are using HTTPs, Make sure you have a certificate installed via the certificate manager (not self signed!), Make sure you have your SIP Configuration tweaked properly to support your network type.. It'll take some fiddling.

Also, I found I had some troubles with latest Firefox 60 with WebRTC. Chromium worked just fine. WebRTC is a very finnicky one.

**Comment by BitCol** [comment]
HTTPs done, with wss proxy as well, with Letsencrypt certificate, all green, when loading the WebRTC phone on the UCP now works ( now meaning with https ) , I can connect with the extension via UCP but cant make call to eachother. peahaps a dialplan ?

**Comment by tiredofit** [comment]
You shouldn't have to setup a dialplan for extension to extension.. Try one *97 (Voicemail) *65, to see if the call connects, and check out your log file /var/log/asterisk/full ?
