### ISSUE TITLE
syntax error in latest build

### ISSUE THREAD

**Issue by my-umd** [tiredofit/docker-freepbx#140]
I've been playing with the image in the past week and could have it installed successfully before yesterday.  I found this error when installing release 4.0.4 (must be the one that is labeled as latest):
[INFO] ** [freepbx] Starting Operator Panel                                                                                                                            
/var/run/s6/etc/cont-init.d/10-freepbx: line 564: syntax error near unexpected token `('                                                                               
/var/run/s6/etc/cont-init.d/10-freepbx: line 564: `   print_info "Web Server Started - Container Initialization Complete - Visit your http(s)://yoursite/${ADMIN_DIRECT
ORY} to administer"'                                                                                                                                                   
[cont-init.d] 10-freepbx: exited 2. 

Also noticed the asterisk version is changed back from 17.2.0 to 16.9.0:
ENV ASTERISK_VERSION=16.9.0
Is there any reason for this downgrade?  Is it possible to revert the image to where it was?

**Comment by tiredofit** [comment]
Sorry about this, new release `4.0.5.1` fixes this error you are having.

Were you having success with 17? We were getting lots of reports that it was not working as expected so rolled back. I would love to hear your use cases and successes and willing to try again.

**Comment by my-umd** [comment]
Thanks @tiredofit, the error is gone now.  Haven't got a chance to test the functionality yet though (will sure to update).
Regarding asterisk v17, I did, sort of, get it to work without much tweaking.  What I have done successfully with the v17 image was to get it installed on my QNAP NAS (have to set network mode to bridge though, NAT mode gave UnixHTTPConnectionPool timeout error), set up (external) databases, (trivial) modifying server name displayed on the dashboard (under 'Welcome to FreePBX', next to 'FreePBX 15.0.16.49'), add admin account, add (two) extension/users (forgot if it's pjsip or the legacy chan_sip), ring other extension in the same (asterisk) system using Zoiper soft phone (one on my PC, one on my cellphone).  However, I hear no sound no matter from which end  I dial (cell or PC).  However, as confessed in https://github.com/tiredofit/docker-freepbx/issues/138, I am a newbie on this.  Thus I don't know who to blame (me or v17).

**Comment by my-umd** [comment]
Also want to add that 'Live network usage' panel on the dashboard is stuck at 'Loading Interface eth0@if22...'. This happens in both the old build and new build, thus it has nothing to do with asterisk v17.

**Comment by my-umd** [comment]
@tiredofit I just tested 4.0.5.1 and was able to make and receive phone calls using legacy chan_sip extensions with Zoiper.  I believe the reason for not being able to hear any voice (my early comment) in my previous try with v17 was because I tried with chan_pjsip extensions, which currently takes the legacy chan_sip port 5060.  I can reproduce this in my new 4.0.5.1 installation.  So going back to your initial question regarding my success with v17, I think the basic function works, except the 'Live network usage' issue that I reported earlier (could also be a problem orignated from my own network environment, appreciate if you have any guess).  Unfortunately, because I am a novice, I can't test advanced functionalities for v17.
I'm closing this issue because the syntax error has been fixed.  Thanks for working on this.

**Comment by my-umd** [comment]
An update on 'Live network usage' panel: found it works in Firefox and Chrome and Edge mobile browser.  I was using Microsoft Edge desktop browser, which reports this error from web deveoper console:
SCRIPT5009: SCRIPT5009: 'EventSource' is not defined                                            config.php (2,1)
