### ISSUE TITLE
How to access FreePBX?

### ISSUE THREAD

**Issue by mihalski** [tiredofit/docker-freepbx#15]
Hi, this is my first attempt at using Asterisk/FreePBX and I followed the instructions as best as I could.
Here is the command I used with an empty /docker/freepbx directory:
```
docker run -d \
  --name freepbx \
  --restart=always \
  --net=host \
  --privileged \
  -v /docker/freepbx/certs:/certs \
  -v /docker/freepbx/www:/www/freepbx \
  -v /docker/freepbx/log:/var/log/ \
  -v /docker/freepbx/data:/data \
  -e DB_EMBEDDED=TRUE \
  tiredofit/freepbx
```
If I then go to log in I simply get:
```
Apache2 Debian Default Page
```
Is there something I am missing?

**Comment by tiredofit** [comment]
The install is rather intense when first starting up, can you give me the log output?

**Comment by mihalski** [comment]
Sure, if you mean the output of docker logs freepbx.

[dockerlogs.txt.gz](https://github.com/tiredofit/docker-freepbx/files/1905713/dockerlogs.txt.gz)

**Comment by mihalski** [comment]
Well that was the missing bit on information.. I had NO idea that /admin was required in the path of the URL.

So far so good, now I just have to learn how to use it!

**Comment by tiredofit** [comment]
Something is up as it should auto redirect to the /admin folder.. 
Good luck! It's a long hairpulling journey into SIP/IAX/VOIP you are taking :)
