### ISSUE TITLE
Can't use persistent volume

### ISSUE THREAD

**Issue by Rexz34** [tiredofit/docker-freepbx#156]
I am currently using portainer to manage my docker install. I am able to install freepbx if I don't declare any persistent volume, however if I declare a volume for /data I hit a snag when trying to install:

chowning directories...

 8402/8402 [============================] 100%

In Process.php line 239:
                                                
  The command "/usr/sbin/fwconsole chown" failed.  
                                               
  Exit Code: 126(Invoked command cannot execute)                                                   

  Working directory: /usr/src/freepbx              
                                                
  Output:                                          

  ================                                 

                                                

                                               
  Error Output:                                    
  ================                                 
  sh: 1: /usr/sbin/fwconsole: Permission denied

Any idea what could be happening?

**Comment by ptruman** [comment]
Your mount is probably on a host partition which is mounted with noexec
Edit your /etc/fstab and remove "noexec" from the mount line, reboot - try again 👍

**Comment by Rexz34** [comment]
Wow. That actually fixed it! Weird as I have installed so many containers before, yet this one was the only one that caused this issue. Thank you @ptruman :)

**Comment by ptruman** [comment]
Welcome! (I had the same problem on another container)  👍
