### ISSUE TITLE
Let's Encrypt Certificate generation from FreePBX admin

### ISSUE THREAD

**Issue by alenas** [tiredofit/docker-freepbx#168]
Hi,

Have the latest version of FreePBX docker image.
I tried to generate Let's Encrypt Certificate from FreePBX Certificate Management, but it fails with 403, because of an issue with folder mappings or something.
For example:

I try to generate certificate, then I get error:
Error 'Requested 'http://myvoip.com//.freepbx-known/5a80be1a0d320e7db0e8a5290c428dda' - 403 Forbidden Forbidden You don't have permission to access this resource. Apache/2.4.38 (Debian) Server at xxxx Port 80 ' when requesting http://myvoip.com/.freepbx-known/5a80be1a0d320e7db0e8a5290c428dda

I checked data folder and I can see that
file **exists** here: /var/www/html/.freepbx-known/5a80be1a0d320e7db0e8a5290c428dda
but in apache log it is looking for the file in here: AH01630: client denied by server configuration: **/var/www/html/ucp/.freepbx-known**
(in UCP instead of root).

Is this error related to FreePBX bug or my docker image misconfiguration or what :D

**Comment by tiredofit** [comment]
I've never really use the internal letsencrypt functions of FreePBX to be honest and a.ways have thrown them inside a proxy.
My advice would be to play around with some of the apache configuration files to allow your .freepbx-known (thats a weird one, I'm used to a .well-known). You could also try playing with the hack I created to make UCP first by setting `UCP_FIRST=FALSE` as an environment variable. 

Unfortunately I'm going to have to hope others come and give their advice and experience.

**Comment by alenas** [comment]
Thanks Dave, UCP_FIRST=FALSE fixed it.
