### ISSUE TITLE
Web port other than 80?

### ISSUE THREAD

**Issue by eyeruleall** [tiredofit/docker-freepbx#17]
I would like to put in a request for an environment variable to control the web port so I can have the option keep the container on host networking.

**Comment by tiredofit** [comment]
Sure, that was easy enough and had been a nice to have for a while. I've just committed that and you should be seeing it on the Docker Hub within the next few hours.
Use `HTTP_PORT` or `HTTPS_PORT` to set it away from the default 80/443.
Let me know if it gives you any issues.

**Comment by eyeruleall** [comment]
Apache is still only looking at port 80, even with the new HTTP_PORT option set.

**Comment by tiredofit** [comment]
Found a spot where 80 was hiding - Just pushed the fix - building on Docker Hub now..

**Comment by eyeruleall** [comment]
we're getting closer. I get the debian apache page, but can't load admin. 
"(98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down"
shows up in logs, even though HTTP_PORT=8082 is set as an env var.

**Comment by tiredofit** [comment]
OK, well this embarrassing. I'll need a few days to be able to get a fresh environment setup on my end and I'll try to lick this once and for all. To be continued.

**Comment by tiredofit** [comment]
Sorry, had to deal with a weekend. Problem was a missing variable declaration. Latest Push (2.41) / Docker hub :latest will have the fix. Confirmed and tested on my end.

If you do see it again, list me the contents of your /etc/apache2/ports.conf and /etc/apache2/sites-enabled/000-default.conf when the container is running.

**Comment by eyeruleall** [comment]
Still not working. :-(

Docker-compose section: 
 freepbx:
    container_name: freepbx
    image: tiredofit/freepbx
    restart: always
    network_mode: host
    volumes:
      - ./freepbx/certs:/certs
      - ./freepbx/data:/data
      - ./freepbx/logs:/var/log
      - ./freepbx/data/www:/var/www/html
      - ./freepbx/db:/var/lib/mysql
    environment:
      - HTTP_PORT=8082
      - ENABLE_ZABBIX=FALSE
      - ENABLE_SMTP=FALSE
      - ENABLE_FOP=FALSE
      - ENABLE_CRON=FALSE
      - RTP_START=10000
      - RTP_FINISH=20000
      - DB_EMBEDDED=TRUE
    cap_add:
      - NET_ADMIN
    privileged: true

ports.conf:

Listen 80

<IfModule ssl_module>
	Listen 443
</IfModule>

<IfModule mod_gnutls.c>
	Listen 443
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

apache2/sites-enabled/000-default.conf:

Listen 73

ExtendedStatus On

<VirtualHost *:73>
CustomLog /dev/null common
ErrorLog /dev/null

<Location /server-status>
    SetHandler server-status
    Order deny,allow
    Deny from all
    Allow from localhost
</Location>
</VirtualHost>

<VirtualHost *:8082>
    DocumentRoot /var/www/html/ucp
    Alias "/admin" "/var/www/html/admin"
    Alias "/ucp" "/var/www/html/ucp"

  ErrorLog /var/log/apache2/error.log
  CustomLog /var/log/apache2/access.log common
  <Location /server-status>
    SetHandler server-status
    Order deny,allow
    Deny from all
 </Location>
</VirtualHost>

**Comment by eyeruleall** [comment]
We're almost there. I don't know if it was my setup or not, but my phone wouldn't connect. Had an error in the full log that said port 5060 was already in use. I stopped and started the freepbx container, and got an error about ports.conf

`docker exec -it freepbx cat /etc/apache2/ports.conf`
```
# If you just change the port or add more ports here, you will likely also
# have to change the VirtualHost statement in
# /etc/apache2/sites-enabled/000-default.conf

Listen 808282

<IfModule ssl_module>
        Listen 443
</IfModule>

<IfModule mod_gnutls.c>
        Listen 443
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet`
```
HTTP_PORT env var is set to 8082, but it's setting ports.conf 808282 for some reason upon restart.

**Comment by tiredofit** [comment]
So close. I've got a new image that uses a different method. Instead of modifying the in place `ports.conf` this new one will create a brand new one on each container start. Building now..

**Comment by eyeruleall** [comment]
So close. Brought the container up and let it install, got the admin page, and restarted the container. The web port is surviving the restart, but I think we broke something else. "Access denied for user 'freepbxuser'@'localhost'::SQLSTATE[HY000] [1698] Access denied for user 'freepbxuser'@'localhost'" after container restart with embedded DB.

**Comment by tiredofit** [comment]
Glad the ports are working properly now..
What you are seeing there is a failure for it to connect to the DB. Freepbx in their default install creates a random string for a password, and it's either getting overwritten or not saved. Yes, it's probably me at some point overwriting one of the files. I haven't used the DB_EMBEDDED option other than just building it in on a request for someone - Freepbx puts it's SQL credentials I believe in `/etc/amportal.conf` or `/etc/freepbx.conf`. I built this to work with external DBs so if you wanted to go down the approach of how I'm using it you could deploy a seperate MariaDB container (tiredofit/mariadb, or even official, whatever) and just expose 127.0.0.1:3306:3306 if you wanted to stay closer to the way I designed it.

That being said I'll spin up another copy with `DB_EMBEDDED=TRUE` and see if I can sort heads from tails. Hang in there. Will be a few more days till I can get to it..

**Comment by billbogaiv** [comment]
I have encountered the same `Access denied for user 'freepbxuser'@'localhost'...` error after stopping/starting the container using `DB_EMBEDDED=TRUE`. When I log into the `mysql` instance, querying `select * from mysql.user;` only returns the `root` account. If I add a user and confirm it's in the table and then restart the container again, that new user is no longer in the table. Additionally, if I query any table in the `asterisk` DB, I get `Table 'asterisk.{tableName}' doesn't exist in engine`–which again points back to the `mysql` DB getting "restored" to some default state. I'm not sure what's causing this. Doesn't appear to be anything that re-copies data in the `/var/lib/mysql/mysql` directory if it already exists. 🤷‍♂️

**Comment by tiredofit** [comment]
Closing as all issues have been resolved with recent releases.
