### ISSUE TITLE
Using Traefik in a different Docker Container

### ISSUE THREAD

**Issue by woobenjamin** [tiredofit/docker-freepbx#198]
### Summary

I currently have a traefik container running. 
I'm trying to get a let's encrypt certificate so that I can connect using TLS for my endpoints, and TLS for my trunks. I really hope my question isn't too far out-of-scope.

### Steps to reproduce

I'm basing everything off the example/docker-compose.yml.
for the tiredofit/docker-freepbx, this is the traefik entries:
```
    labels:
      - "traefik.enable=true"
        # Not required
      # - "traefik.docker.network=traefik"
      ## HTTP Routers
      - "traefik.http.routers.pbx-rtr.tls=true"
      - "traefik.http.routers.pbx-rtr.entrypoints=https"
      - "traefik.http.routers.pbx-rtr.rule=Host(`pbx.example.net`)"
      ## HTTP Services
      - "traefik.http.routers.pbx-rtr.service=pbx-svc"
      - "traefik.http.services.pbx-svc.loadbalancer.server.port=$FREEPBX_PORT"
      ## Middlewares
        # Use no authentication chain because it has to be fully exposed to the Internet
      - "traefik.http.routers.pbx-rtr.middlewares=chain-no-auth@file"
```
in my traefik docker docker-compose, the labels look like this:
```
    labels:
      - "traefik.enable=true"
      ### HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      ### HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.example.net`)"
      - "traefik.http.routers.traefik-rtr.tls=true"
```

### What is the expected *correct* behavior?

I'm getting the Let's Encrypt error:
```
Self test error: Pest_Forbidden - 403 Forbidden Forbidden You don't have permission to access this resource. Apache/2.4.38 (Debian) Server at pbx.example.net Port 80
Does DNS for pbx.example.net resolve correctly? Local DNS result: 111.222.333.444, External DNS result: 111.222.333.444
The LetsEncrypt servers only send challenge queries to port 80. Certificate requests will fail if public access via port 80 is not available.
Processing: pbx.example.net, Local IP: 111.222.333.444, Public IP: 111.222.333.444
Self test: trying http://pbx.example.net/.freepbx-known/ac14069febca3951ee988bf3ad760daf
Self test error: Pest_Forbidden - 403 Forbidden

Forbidden
You don't have permission to access this resource.

Apache/2.4.38 (Debian) Server at pbx.example.net Port 80
```

It's pretty clear it is a port 80 thing, but what I don't know is whether I need to make changes to my traefik config or the freepbx config. (btw, UDP works perfectly) I understand troubleshooting the traefik config is definitely outside the scope of this forum.

### Environment

- Image version / tag:  latest
- Host OS: Ubuntu/Docker/Docker-Compose/docker-freepbx

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>
See above

**Comment by cooshal** [comment]
hey @thisisbenwoo, did you find anything regarding this issue?

**Comment by woobenjamin** [comment]
I have not. I have moved on to other concerns. That said, I am confident that with further research, someone has already answered this question. I cannot believe that this would be something that no one else has encountered.
