### ISSUE TITLE
why dont work? 

### ISSUE THREAD

**Issue by krll-k** [tiredofit/docker-freepbx#22]
![image](https://user-images.githubusercontent.com/2174805/44290309-cdf99680-a280-11e8-9c89-d02829795fa9.png)

![image](https://user-images.githubusercontent.com/2174805/44290250-7bb87580-a280-11e8-8d5b-129f51ee186e.png)

**Comment by rene-gomez** [comment]
Hello, you need expose 80 port on docker compose file or need add the nginx reverse proxy.

best regards
