### ISSUE TITLE
Good container install but wont work after a container restart.

### ISSUE THREAD

**Issue by enforcer1064** [tiredofit/docker-freepbx#23]
I installed the FreePbx docker as per this post: 

```
 docker run -d \
  --name freepbx \
  --restart=always \
  --net=host \
  --privileged \
  -v /docker/freepbx/certs:/certs \
  -v /docker/freepbx/www:/www/freepbx \
  -v /docker/freepbx/log:/var/log/ \
  -v /docker/freepbx/data:/data \
  -e DB_EMBEDDED=TRUE \
  tiredofit/freepbx
```

and it runs perfectly fine.
But if I restart the container for any reason - it doesnt seem to start back up.
The /admin page shows this error
```
Exception (1698)
SQLSTATE[HY000] [1698] Access denied for user 'freepbxuser'@'localhost'::SQLSTATE[HY000] [1698] Access denied for user 'freepbxuser'@'localhost'
```

Can I provide any more info that would help ?

**Comment by tiredofit** [comment]
So close! Since you are running DB_EMBEDDED=TRUE add this to your volumes:
`-v ./docker/freepbx/db:/var/lib/mysql`
Let me know..

**Comment by enforcer1064** [comment]
I added that line into a new install and again it worked first time, but
after restarting the container it didn't work.

'''
Exception (1698)
SQLSTATE[HY000] [1698] Access denied for user
'freepbxuser'@'localhost'::SQLSTATE[HY000]
[1698] Access denied for user 'freepbxuser'@'localhost''''

**Comment by enforcer1064** [comment]
I'm happy to not use the embedded dB if that's causing the issue.

I just need to know how to do that.

**Comment by tiredofit** [comment]
OK Great! Just take a peek in the examples folder of this git repo for the docker-compose.yml file.

https://github.com/tiredofit/docker-freepbx/blob/master/examples/docker-compose.yml

That's pretty much a turnkey solution that's going to get you going immediately with the database seperated and also provide automated db backups for you.

Now, it's based on you using a reverse proxy, but you don't need to use one, as a quick starter just type `docker network create nginx-proxy` and uncomment the # - 80:80 in the ports definition to see it working and be able to persist upon bringing the container up and down. 
it _should_ be as simple as moving that docker-compose.yml file into the directory where you want to store your files and typing docker-compose up -d.
Let me know how you make out.

**Comment by sylhero** [comment]
@tiredofit I did what you mentioned but I got the following error
```
2018-09-25 13:09:05 0 [ERROR] InnoDB: The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages!
2018-09-25 13:09:05 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2018-09-25 13:09:05 0 [Note] InnoDB: Starting shutdown...
```
it seems that the DB can't start

**Comment by JoyceBabu** [comment]
I think I found out why the database is being wiped out after every restart.

https://github.com/tiredofit/docker-freepbx/blob/master/install/etc/cont-init.d/09-mariadb#L14

You are using `-f` for checking the presence of `/var/lib/mysql/mysql`. Since the above path is a directory, it is always matching. You should either use `-e` or `-d`.

**Comment by tiredofit** [comment]
Thank you @JoyceBabu

**Comment by tiredofit** [comment]
Very odd, still timing out for me. I'll give it a few more hours and then build myself and see if I can sneak one in manually.

**Comment by tiredofit** [comment]
I've just done a manual build locally for both tag `:latest` and `2.7`. Enjoy!
