### ISSUE TITLE
Can't change UI language

### ISSUE THREAD

**Issue by sylhero** [tiredofit/docker-freepbx#26]
I installed everything and it's working but when I tried to switch UI language except English nothing works.
![screen shot 2018-10-05 at 10 29 46 pm](https://user-images.githubusercontent.com/4540917/46566524-3f071300-c8ee-11e8-9e1d-91db88bda197.png)

**Comment by tiredofit** [comment]
HI there, that I may not be able to help with. I've only used with English, are there any steps you took to be able to load those additional languages?

**Comment by sylhero** [comment]
@tiredofit sorry for the late reply. I found this on Freepbx https://issues.freepbx.org/browse/FREEPBX-3707 it seems that the GUI language pack depends on the server locales.

**Comment by tiredofit** [comment]
There was someone named @uplinkws who forked my image a couple months ago and was able to add german files to it, however I believe that was only for the Asterisk sound files.  Sounds like you may need to fork as well and add locales to your own image. I will investigate what the size difference will be and see what the possibilities are in coming days..

**Comment by sylhero** [comment]
@tiredofit  I just found the solution to this problem. Here are the steps you need to take:
1. `apt-get update && apt-get install -y debconf locales locale-gen`
2.`vim /etc/locale.gen` and uncomment the locale you want
3. `locale-gen`
4. go back to freepbx UI and switch languages it will work

Hopefully this helps

**Comment by tiredofit** [comment]
Fixed now available with `tiredofit/freepbx:latest` (Freepbx 15, Asterisk 16) and also backported to old branch (`tiredofit/freepbx:14-latest` or `tiredofit/freepbx:14-2.14`)

**Comment by tiredofit** [comment]
Backported to `14-latest`
