### ISSUE TITLE
can't start asterisk when building image from the Dockerfile

### ISSUE THREAD

**Issue by sylhero** [tiredofit/docker-freepbx#28]
I'm trying to build an image from the Dockerfile and it's working but when I start the container I got the following error:
```
STARTING ASTERISK
./start_asterisk: line 45: /usr/sbin/safe_asterisk: No such file or directory
Asterisk Started
** [freepbx] Can't seem to start Asterisk.. Exitting
[cont-init.d] 10-freepbx: exited 1.
[cont-init.d] 99-container-init: executing... 
[cont-init.d] 99-container-init: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by tiredofit** [comment]
I just tried building and it looks like their download location has changed. Likely due to Digium becoming aquired by Sangoma. I'll push a new version shortly when I find the new download link.

**Comment by tiredofit** [comment]
I was right, they altered their download repository a bit. I have modified the Dockerfile accordingly, feel free to git pull/fetch and try to rebuild.
