### ISSUE TITLE
No Swap

### ISSUE THREAD

**Issue by sylhero** [tiredofit/docker-freepbx#29]
I see this message on the dashboard
```
Your system has no swap space. This should be fixed as soon as possible. Once fixed issue a reload to remove this message
```
and I tried to do
```
dd if=/dev/zero of=/swapfile count=1024 bs=1M && \
       chmod 600 /swapfile && \
       mkswap /swapfile && \
       echo '/swapfile swap swap defaults 0 0' >> /etc/fstab && \
       swapon /swapfile
       free -m && \
```
I have swap space available but the message is still persistent. Is there a way to fix it?

**Comment by tiredofit** [comment]
Sorry for delay, Unlikely. This is a very bizarre codebase and how it is making its assumptions are usually in ways that don't translate well with Docker. Safe to ignore.
