### ISSUE TITLE
ivr module support?

### ISSUE THREAD

**Issue by crackers8199** [tiredofit/docker-freepbx#30]
i installed the ivr module and uploaded a custom recording, but i can't get it to play.  when asterisk answers the call, it just goes to silence and the ivr doesn't actually work...is there any way to get the ivr module working with this image?

**Comment by tiredofit** [comment]
Hi Matt, 
I haven't experienced such an issue. In fact on Friday was as recent that I had used the IVR module on our production system. This goes a bit out of the scope of the Docker image and more so of the FreePBX support, but I can give a few hints or assumptions as I'm just guessing here as I'm not sure exactly what has been configured.

- Try using WAV or SLN for the uploaded file
- Try reading the asterisk `full` logfile when making an incoming call to see whats actually happening, it should in detail list out what announcement it is playing - and if an error, should let you know.
- Try using a different SIP client to test your incoming call (7777)
- Could it be something with your networking causing the error?

Good luck!

**Comment by crackers8199** [comment]
what confused me though is that if i look in the web gui under system recordings, i can play the recording just fine...so it is in the system and doesn't appear to be corrupted.  i just can't get it to play when asterisk actually answers the call and tries to go thru the IVR...it also doesn't seem to accept any of the IVR inputs.  i only have one (press 1 to go to the main extension), but nothing happens no matter how many times i press 1...

**Comment by crackers8199** [comment]
[2018-10-29 15:46:46] DEBUG[5085][C-00000002]: media_cache.c:252 ast_media_cache_retrieve: Failed to obtain media at 'custom/no-solicitors'

the file is there, though.  i can see it...and like i said, it plays through the GUI.

**Comment by crackers8199** [comment]
it's not just custom recordings, it seems it won't play ANY recordings. even system ones.

unless i'm doing something wrong, this makes no sense to me.  i have it set up exactly the same as i did in my vm, but it worked there and i can't for the life of me get it working with the docker image.

**Comment by crackers8199** [comment]
@tiredofit  any ideas based on my additional info?  i appreciate you trying to assist, i don't see how this can be a freepbx issue though unless i just have something configured wrong...but then i'm just using your default config.  this worked when i created a vm with the latest freepbx distro image, but does not work in the docker image.

**Comment by tiredofit** [comment]
Take a peek inside the container in /var/lib/asterisk/sounds/en/custom just to make sure you have the file in there. I wonder if it may help if you convert to a different format. What was your source format for uploading?
The thing that looks a bit off is that there is no extension on your file.

**Comment by tiredofit** [comment]
Just thinking a bit more about this, how are you accessing the system? By an internet trunk via a POTS / Mobile phone? Through a soft phone? I spoke to one of my systems guys and he has not seen any issues recently with bad updates from FreePBX for their IVR module. We are seeing issues with the Pinsets module in the past month, but IVR has been good.

**Comment by crackers8199** [comment]
POTS, connected via an obi110.


On Tue, Oct 30, 2018, at 12:45 PM, Dave Conroy wrote:
> Just thinking a bit more about this, how are you accessing the system?
> By an internet trunk via a POTS / Mobile phone? Through a soft phone?
> I spoke to one of my systems guys and he has not seen any issues
> recently with bad updates from FreePBX for their IVR module. We are
> seeing issues with the Pinsets module in the past month, but IVR has
> been good.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/tiredofit/docker-freepbx/issues/30#issuecomment-434442825

**Comment by crackers8199** [comment]
also of note: 1) the files are there, i can see them in the directory.  and 2) this also seems to happen even with the default system sounds.

**Comment by tiredofit** [comment]
That is strange. So it cancels out any weirdness with NAT that I was sort of hoping to uncover.
Any possibility you can roll back your IVR version to a previous version? I believe you can in Module Admin select IVR and try a previous version. 
We are using: IVR 14.04, Announcements (which I believe also is suspect) 13.0.7.3
