### ISSUE TITLE
unable to use fax because res_fax_spandsp is missing

### ISSUE THREAD

**Issue by si458** [tiredofit/docker-freepbx#40]
ERROR: No FAX modules detected!
Fax-related dialplan will NOT be generated.
This module requires Fax for Asterisk (res_fax_digium.so) or spandsp based app_fax (res_fax_spandsp.so) to function.

it appears during asterisk build, its only building app_fax and it NEEDS to also include res_fax_spandsp

REF: https://www.informaticapressapochista.com/asterisk/add-res_fax_spandsp_asterisk13/

**Comment by tiredofit** [comment]
To be included in upcoming `3.1` release

**Comment by tiredofit** [comment]
Released!
