### ISSUE TITLE
PHP Component Zend Guard Loader is required but missing from you PHP installation.

### ISSUE THREAD

**Issue by rene-gomez** [tiredofit/docker-freepbx#41]
Hello.

I try install the System Administration module, but, i can't because the webpage say:

> PHP Component Zend Guard Loader is required but missing from you PHP installation.

Some modules need the System Administrador module.

Can you support us?

Best regards.

Rene

**Comment by tiredofit** [comment]
Hi Rene,
I haven't had much luck with the Commercial Modules running under Debian. 5 years back it was easier to get the commercial modules into an Open Source installation but has become harder. If you are able to find a guide on the internet, I'd be glad to integrate it for you.
