### ISSUE TITLE
asterisk cache is not writable

### ISSUE THREAD

**Issue by sylhero** [tiredofit/docker-freepbx#45]
![freepbx](https://user-images.githubusercontent.com/4540917/49816682-69d17580-fd3c-11e8-9e60-4e6491f3c745.png)

**Comment by sylhero** [comment]
it happens recently

**Comment by tiredofit** [comment]
Try restarting the container - permissions get reset upon restart, otherwise you can quickly solve by entering inside the container
```bash
docker exec -it yourcontainername bash
chown -R asterisk /var/spool/asterisk
```

**Comment by sylhero** [comment]
is there  a way we can fix it from the Dockerfile? I added `chown -R asterisk /var/spool/asterisk` at the end of the dockerfile but still have the same problem

**Comment by tiredofit** [comment]
I'm afraid the Dockerfile won't fix what's happening on your end.
Can you do me a favor and get me a ls -l listing of your cache folder? There must be something writing to it that is not running the asterisk folder. As each time the container boots up we reset the permissions but it sounds like something else is running in there.

(You can see line 75 of install/etc/cont-init.d/10-freepbx in this repo to see the permissions reset. You'll notice I am applying the permissions to /data as that's where is actually exists based on the data persistence hacks I perform when building the image).

**Comment by rene-gomez** [comment]
Hello, this is my result:

I deleted my volumes and containers to start from docker-compose and now have the same problem too.

```
root@80caa8a46613:/var/spool/asterisk/cache# ls -l
total 4
drwxr-xr-x 2 root root 4096 Dec 12 15:18 c9
root@80caa8a46613:/var/spool/asterisk/cache#

```

**Comment by tiredofit** [comment]
Thanks for this. I wonder what has changed. In fact, I don't even have a /var/spool/asterisk cache folder :)
Investigating with a fresh install.

**Comment by rene-gomez** [comment]
Hello

@tiredofit  do you know any problem.

Today i deleted everyting i run: docker system prune -a and i deteled all.

When I run Docker-compose up -d again, i can see this problem.

Maybe the debian base have an new bug?

Best regards.

Rene

**Comment by tiredofit** [comment]
Hi Rene, I'm actually seeing major problems with new installs right now.
The GPG keys are not refreshing for me, the PHP repository is now changed, and any downloads fo the freepbx modules are failing. I haven't had a successful build yet to be able to push some changes to support your cache permissions issue. I'll have a few hours of time on Monday to be able to go at this again.

**Comment by tiredofit** [comment]
Hi @rene-gomez . I have just put together a maintenance release (Tag 2.12) that is being built on the DockerHub now which should (?) get you back in business.

Changelog:
```
## 2.12 - 2018-12-27 

* Sort Defaults in Startup Script (cosmetic)
* Add cache dir upon first startup
* Fix internal ports exposure
* Change GPG Keyserver
* Change PHP Packages Source Location
* Update MariaDB Connector
* Fix Database Sanity Tests
* Reorder Module Download
* Add Warning for Self Signed Certificate
* Stop using edge versions on initial bootup, problems have been resolved which caused this on upstream

```

**Comment by rene-gomez** [comment]
Cool!, this release should be fix to SQL problems too?

Best regards.

**Comment by tiredofit** [comment]
That I could never figure out but based on your logs in the other issue semed to be all related to an incomplete install when the image does the git pull... Let me know.
