### ISSUE TITLE
Install on Synology DS916+ NAS

### ISSUE THREAD

**Issue by shahfar** [tiredofit/docker-freepbx#50]
Hi,

I have tried installing this multiple times and only managed to see freepbx being pulled once, only to see that the core module does not install once I login to the web console. During all other times, the instance just throws keep alive events and does not pull  the freepbx binaries to install (have kept it running over night so its not time related). Am I doing something wrong here? Have attached the log for your reference. Thank you in advance for your help!

[tiredofit-freepbx2 (1).txt](https://github.com/tiredofit/docker-freepbx/files/2777932/tiredofit-freepbx2.1.txt)

**Comment by sylhero** [comment]
https://github.com/tiredofit/docker-freepbx/issues/49

**Comment by shahfar** [comment]
Thanks for that @sylhero 
Is there a way around this?

**Comment by licutis** [comment]
There seem to be upstream issues with freepbx and the containers configuration scripts.

**Comment by licutis** [comment]
There seem to be upstream issues with freepbx and the containers configuration scripts. This issue is not limited to Install on Synology DS916+ NAS.

**Comment by licutis** [comment]
There seem to be upstream issues with freepbx. This issue is not limited to Install on Synology DS916+ NAS.

**Comment by tiredofit** [comment]
This is now resolved - The problem was related to FreePBX sources not this image. New image now exists for Freepbx 15/Asterisk 16. Give it a try!
