### ISSUE TITLE
UPCOMING BREAKING IMAGE CHANGES

### ISSUE THREAD

**Issue by tiredofit** [tiredofit/docker-freepbx#51]
To all,
In the coming days I will release a new series of images that track Asterisk 16 and Freepbx 15.
Your existing installations will not automatically upgrade to this version as jumping from major releases will introduce breakages. I have created a new branch `14` which tracks the present day version using Asterisk 14.78 and Freepbx 14.

I strongly urge all users ahead of time to alter their configuration files when launching this container to pull from `tiredofit/freepbx:14-latest` as opposed to `tiredofit/freepbx:latest`.

If you do not do this the next time you pull the image you will be presented with an error message causing the container not to function until you make this manual change. At present time I haven't figured out a way to do an automatic in place upgrade to support this change.

I will continue to maintain the 14 branch for a period of time yet will be investing most efforts into keeping the new release up to date.

I will update this thread upon any new news.

**Comment by jeffballard** [comment]
Hi

On the docker-compose.yml on branch 14, it attempts to launch tiredofit/freepbx:14, which results in:

$ docker-compose pull
Pulling freepbx-db (tiredofit/mariadb:latest)...
latest: Pulling from tiredofit/mariadb
Digest: sha256:4b312b238c40e64cc1077b857da8be70c10432dee8c9400be8f4aadcd08cd6ac
Status: Image is up to date for tiredofit/mariadb:latest
Pulling freepbx-app (tiredofit/freepbx:14)...
ERROR: manifest for tiredofit/freepbx:14 not found

... which looks like the container on Dockerhub is not tagged with 14?  https://hub.docker.com/r/tiredofit/freepbx/tags  seems to confirm that the container isn't tagged that way.

Thanks!

**Comment by tiredofit** [comment]
Hi Jeff, Looks like I'm a bit preemptive - Docker Hub hasn't built the new image yet and is backlogged.

**Comment by tiredofit** [comment]
That took an incredibly long time for the Docker Hub to build. They are live now. I have added additional checks in upcoming 3.0 release to alert users who may miss this in time, as release is imminent. I will refrain from releasing right away so that users can get caught up in time, however those who wish to sneak a peek can grab from `tiredofit/freepbx:develop`

**Comment by denny666** [comment]
Hi tiredofit,
I had pull docker from "https://hub.docker.com/r/tiredofit/freepbx/", and run image on VM of GCP.
Does this docker has Web GUI like FreePBX Distro?

**Comment by tiredofit** [comment]
Yes it has Web GUI - as it uses Freepbx by default.
I'm going to close this issue as it is a couple years old.
