### ISSUE TITLE
What is the fefault fser for login page ?

### ISSUE THREAD

**Issue by atyenoria** [tiredofit/docker-freepbx#61]
I can't login after docker-compose up in example folder.
![image](https://user-images.githubusercontent.com/7510974/53225774-6bb0a100-36bc-11e9-8148-f354ea19518d.png)

What is the default user?

**Comment by atyenoria** [comment]
asterisk, asteriskpass can't work

**Comment by atyenoria** [comment]
admin,admin also can't work
https://community.freepbx.org/t/what-is-the-default-web-login-password/7180

**Comment by tiredofit** [comment]
Add a `/admin` at the end of your url. That's a feature I've built into the image to put the UCP first. I believe you can also turn it off to make the freepbx console work without the /admin by with `UCP_FIRST=FALSE`

**Comment by atyenoria** [comment]
@tiredofit Thanks! I will try it
