### ISSUE TITLE
"Apply config" -> Error: Did not receive valid response from server

### ISSUE THREAD

**Issue by barhom** [tiredofit/docker-freepbx#65]
Whenever I click "Apply config" I get the following error,

Error: Did not receive valid response from server
XHR response code: 504 XHR responseText: undefined jQuery status: error

The error is when reaching /admin/ajax.php?command=reload.
It gets a 504 error.

**Comment by barhom** [comment]
I tracked it down to:
libraries/BMO/Framework.class.php
public function doReload($passthru=false) {

The following codes simply hangs and does not continue:

> 
>                 $process = new \Symfony\Component\Process\Process($AMPSBIN.'/fwconsole reload --json');
>                 $process->setTimeout(1800);
>                 $process->run();


If I run "fwconsole reload --json" from inside container (bash) it runs fine

**Comment by tiredofit** [comment]
Alot of times we have been seeing these upstream errors from Freepbx - I believe I am going to need to switch to a different method and start pinning stable releases to this image as oposed to just pulling from their git repositories.
I am moving and will be away for a week, once I return I will look into this.

**Comment by barhom** [comment]
@tiredofit were you able to reproduce the same issue?

**Comment by tiredofit** [comment]
Hi @barhom - I cannot recreate on a fresh install. My test scenario involved updating all modules and adding an extension.

**Comment by barhom** [comment]
cant reproduce my problem anymore. closing the issue.

**Comment by barhom** [comment]
@tiredofit actually I was able to reproduce it if I used tag "15-3.3.1". Works good if I dont specify a tag.

**Comment by tj22777** [comment]
Hi Guys, I installed a fresh new FreePBX 16.0.40.6
But then still got this issue.
How to fix this, why there FreePBX always having this issue on all of its new version?
