### ISSUE TITLE
The links are broken

### ISSUE THREAD

**Issue by microtecsistemas** [tiredofit/docker-freepbx#7]
Hello, congratulations on the work.

Some links are broken on your [hub.docker page](https://hub.docker.com/r/tiredofit/freepbx/), such as the link: https://hub.docker.com/r/tiredofit/freepbx/examples/docker-compose.yml

**Comment by tiredofit** [comment]
Ahh - I need to be more careful with my documentation! It should be linking to github instead. I build these images for an organization, and once built share them with the public, and we have our registry/git all on the same url. I will fix shortly for completion! Enjoy the image and my others.

**Comment by microtecsistemas** [comment]
Hello, thank you for your reply that now made me understand the reason. I understand perfectly.
Once again, congratulations on your work.
Best Regards
