### ISSUE TITLE
After use docker macvlan,can't access web

### ISSUE THREAD

**Issue by ZhengSaisi** [tiredofit/docker-freepbx#70]
After use docker macvlan,can't access web

**Comment by zzzacbbt** [comment]
version: '3'

services:
  freepbx-app:
    container_name: freepbx-app
    image: tiredofit/freepbx
    ports:
     #### If you aren't using a reverse proxy
      - 80:80
     #### If you want SSL Support and not using a reverse proxy
     #- 443:443
      - 5060:5060
      - 5160:5160
      - 18000-18100:18000-18100/udp
     #### Flash Operator Panel
      - 4445:4445
    volumes:
      - ./certs:/certs
      - ./data:/data
      - ./logs:/var/log
      - ./data/www:/var/www/html
     ### Only Enable this option below if you set DB_EMBEDDED=TRUE
     #- ./db:/var/lib/mysql
     ### You can drop custom files overtop of the image if you have made modifications to modules/css/whatever - Use with care
     #- ./assets/custom:/assets/custom

    environment:
      - VIRTUAL_HOST=hostname.example.com
      - VIRTUAL_NETWORK=nginx-proxy
     ### If you want to connect to the SSL Enabled Container
     #- VIRTUAL_PORT=443
     #- VIRTUAL_PROTO=https
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=hostname.example.com
      - LETSENCRYPT_EMAIL=email@example.com

      - ZABBIX_HOSTNAME=freepbx-app

      - RTP_START=18000
      - RTP_FINISH=18100

     ## Use for External MySQL Server
      - DB_EMBEDDED=FALSE

     ### These are only necessary if DB_EMBEDDED=FALSE
      - DB_HOST=freepbx-db
      - DB_PORT=3306
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asteriskpass

     ### If you are using TLS Support for Apache to listen on 443 in the container drop them in /certs and set these:
     #- TLS_CERT=cert.pem
     #- TLS_KEY=key.pem

    restart: always
    networks:
      test-net:
        ipv4_address: 20.20.5.26

    ### These final lines are for Fail2ban. If you don't want, comment and also add ENABLE_FAIL2BAN=FALSE to your environment
    cap_add:
      - NET_ADMIN
    privileged: true

  freepbx-db:
    container_name: freepbx-db
    image: tiredofit/mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=asterisk
      - MYSQL_USER=asterisk
      - MYSQL_PASSWORD=asteriskpass
    networks:
      test-net:
        ipv4_address: 20.20.5.27

  freepbx-db-backup:
    container_name: freepbx-db-backup
    image: tiredofit/db-backup
    links:
     - freepbx-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - ZABBIX_HOSTNAME=freepbx-db-backup
      - DB_HOST=freepbx-db
      - DB_TYPE=mariadb
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asteriskpass
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    networks:
      test-net:
        ipv4_address: 20.20.5.28
    restart: always

networks:
  test-net:
    driver: macvlan
    driver_opts:
      parent: enp4s0.45
    ipam:
      config:
        - subnet: 20.20.5.0/24
          gateway: 20.20.5.1
          ip_range: 20.20.5.24/29
          aux_addresses:
            voip_gateway: 20.20.5.24




enp4s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::4327:6963:ab4d:b2cc  prefixlen 64  scopeid 0x20<link>
        ether 08:57:00:e7:1d:bf  txqueuelen 1000  (Ethernet)
        RX packets 1788021  bytes 236900620 (225.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1057395  bytes 383001707 (365.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
enp4s0.45: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 20.20.5.1  netmask 255.255.255.0  broadcast 20.20.5.255
        inet6 fe80::cd64:317:e675:5797  prefixlen 64  scopeid 0x20<link>
        ether 08:57:00:e7:1d:bf  txqueuelen 1000  (Ethernet)
        RX packets 244881  bytes 26769813 (25.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 226921  bytes 58068932 (55.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
macvlan_voip: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 20.20.5.25  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fe80::4a7:ccff:fe8c:48b4  prefixlen 64  scopeid 0x20<link>
        ether 06:a7:cc:8c:48:b4  txqueuelen 1000  (Ethernet)
        RX packets 36235  bytes 2544349 (2.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 42251  bytes 101003109 (96.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
macvlan_voip: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 20.20.5.25  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fe80::4a7:ccff:fe8c:48b4  prefixlen 64  scopeid 0x20<link>
        ether 06:a7:cc:8c:48:b4  txqueuelen 1000  (Ethernet)
        RX packets 36235  bytes 2544349 (2.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 42251  bytes 101003109 (96.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by ZhengSaisi** [comment]
![image](https://user-images.githubusercontent.com/38638768/55697058-5389ac80-59f2-11e9-93ad-001fcd2f1789.png)
![image](https://user-images.githubusercontent.com/38638768/55697083-62705f00-59f2-11e9-925c-594350b33d6e.png)
![image](https://user-images.githubusercontent.com/38638768/55697104-75832f00-59f2-11e9-8c98-7c80c7b8ba99.png)
![image](https://user-images.githubusercontent.com/38638768/55697115-803dc400-59f2-11e9-861a-3d0ead52ca6a.png)
![image](https://user-images.githubusercontent.com/38638768/55697129-892e9580-59f2-11e9-8c11-338ccc51bb06.png)

**Comment by ZhengSaisi** [comment]
@tiredofit I want to use 20.20.5.26/admin to access web from 20.20.5.172,it was failed

**Comment by ZhengSaisi** [comment]
Now,Everything is Ok.just the browser's problem.: )
