### ISSUE TITLE
sendmail

### ISSUE THREAD

**Issue by barhom** [tiredofit/docker-freepbx#72]
Is there anyway to configure sendmail in this docker?

**Comment by tiredofit** [comment]
Yes absolutely.
I believe however that SMTP is handled in Freepbx by the php functionality, however I have built routines to support this. If you want to use sendmail from console or other applications that is also available, however I am using msmtp.

The options for mailing are actually detailed in the images base image (which is tiredofit/debian) but here you go:

Parameter | Description
-- | --
ENABLE_SMTP_GMAIL | Add setting to supoprt sending through Gmail SMTP - Default: FALSE
SMTP_HOST | Hostname of SMTP Server - Default: postfix-relay
SMTP_PORT | Port of SMTP Server - Default: 25
SMTP_DOMAIN | HELO Domain - Default: docker
SMTP_MAILDOMAIN | Mail Domain From - Default: example.org
SMTP_AUTHENTICATION | SMTP Authentication - Default: none
SMTP_USER | Enable SMTP services - Default: user
SMTP_PASS | Enable SMTP Password Agent - Default: password
SMTP_TLS | Use TLS - Default: off
SMTP_STARTTLS | Start TLS from within Dession - Default: off
SMTP_TLSCERTCHECK | Check remote certificate - Default: off

Let me know if that gets you movin!

**Comment by barhom** [comment]
> I believe however that SMTP is handled in Freepbx by the php functionality, however I have built routines to support this. If you want to use sendmail from console or other applications that is also available, however I am using msmtp.

I am trying to get the voicemail-to-email functionality working.
Let me try this and get back to you!

**Comment by tiredofit** [comment]
Sure thing. If it doesn't work I remember custom building a voicemail to email hack that I will go dig up and share with you. I can't recall what it was for but it might have been just as simple as I didn't agree with how bare the original notifications looked.

**Comment by barhom** [comment]
Got it working via mailgun. But exactly like you said it isnt in the format that I would like.
So I'm going to write a small script to send the voicemails to me instead.

No need for you to dig up your old code, its quite simple to read the folder and email it.

Thanks
