### ISSUE TITLE
UCP is broken

### ISSUE THREAD

**Issue by sylhero** [tiredofit/docker-freepbx#74]
Downloading module 'ucp'
Processing ucp
Verifying local module download...Verified
Extracting...Done
Download completed in 7 seconds
Updating tables ucp_sessions...Done
sh: 1: icu-config: not found
icu is not installed. You need to run: yum install icu libicu-devel
Unable to install module ucp:
 - Failed to run installation scripts

**Comment by sylhero** [comment]
I tried to download the icu directly 
```
wget http://download.icu-project.org/files/icu4c/52.1/icu4c-52_1-RHEL6-x64.tgz
tar xf icu4c-52_1-RHEL6-x64.tgz
```
it works but 
```
Downloading module 'ucp'
Processing ucp
Verifying local module download...Verified
Extracting...Done
Download completed in 4 seconds
Updating tables ucp_sessions...Done
Installing/Updating Required Libraries. This may take a while...The following messages are ONLY FOR DEBUGGING. Ignore anything that says 'WARN' or is just a warning
Found npm-cache v0.7.0
Running installation..
[npm-cache] [INFO] using /home/asterisk/.package_cache as cache directory
[npm-cache] [INFO] [composer] Dependency config file /var/www/html/admin/modules/ucp/node/composer.json does not exist. Skipping install
[npm-cache] [INFO] [npm] config file exists
[npm-cache] [INFO] [npm] cli exists
[npm-cache] [INFO] [npm] hash of /var/www/html/admin/modules/ucp/node/package.json: 76ab6df0c1940daaf47b99501250de86
[npm-cache] [INFO] [npm] running [npm install]...
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead

> mariasql@0.2.6 install /var/www/html/admin/modules/ucp/node/node_modules/mariasql
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn ENOMEM
gyp ERR! stack     at ChildProcess.spawn (internal/child_process.js:371:11)
gyp ERR! stack     at Object.spawn (child_process.js:561:9)
gyp ERR! stack     at Gyp.spawn (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:180:26)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:334:20
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:285:20
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:159:5)
gyp ERR! System Linux 4.4.0-131-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/html/admin/modules/ucp/node/node_modules/mariasql
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! mariasql@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the mariasql@0.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/asterisk/.npm/_logs/2019-04-12T21_28_03_273Z-debug.log
[npm-cache] [ERROR] [npm] error running npm install
[npm-cache] [ERROR] error installing dependencies

Failed updating libraries!
Stopping old running processes...Done
Refreshing all UCP Assets, this could take a while...
Generating Module Scripts...Done
Generating Module CSS...Done
Generating Main Scripts...Done
Generating Main CSS...Done
Done!
Generating CSS...Done
Module ucp successfully installed
Updating Hooks...Done
Chowning directories...Done
```
and the UCP is not running
![Screen Shot 2019-04-12 at 5 47 40 PM](https://user-images.githubusercontent.com/4540917/56067982-2834f380-5d4b-11e9-91c6-1c6e3d2911ba.png)

**Comment by sylhero** [comment]
@tiredofit any thoughts about this?

**Comment by tiredofit** [comment]
Can you try uninstalling and reinstalling the pm2 daemon? It should be a plugin.

**Comment by sylhero** [comment]
@tiredofit no luck

**Comment by sylhero** [comment]
@tiredofit https://community.freepbx.org/t/ucp-upgrade-error/58273

**Comment by sylhero** [comment]
fixed by https://github.com/tiredofit/docker-freepbx/pull/76

**Comment by wilibox** [comment]
I tried to reinstall ucp via module admin and got his error:
>Downloading and Installing ucp
Downloading ucp 
Installing ucp
Untarring..Done
Updating tables ucp_sessions...Done
icu is not installed. You need to run: yum install icu libicu-devel
Error(s) installing ucp:
Failed to run installation scripts

However, dpkg reports some icu libs already installed:
>dpkg -l |grep icu
ii  icu-devtools                                          64.1-0.1+0~20190410090943.5+str amd64                           Development utilities for International Components for Unicode
ii  libicu-dev:amd64                                      64.1-0.1+0~20190410090943.5+str amd64                           Development files for International Components for Unicode
ii  libicu57:amd64                                        57.1-6+deb9u2                   amd64                           International Components for Unicode
ii  libicu64:amd64                                        64.1-0.1+0~20190410090943.5+str amd64                           International Components for Unicode

**Comment by wilibox** [comment]
And I believe it is related to npm error:
>4216 verbose stack Error: mariasql@0.2.6 install: `node-gyp rebuild`
4216 verbose stack Exit status 1
4216 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
4216 verbose stack     at EventEmitter.emit (events.js:196:13)
4216 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
4216 verbose stack     at ChildProcess.emit (events.js:196:13)
4216 verbose stack     at maybeClose (internal/child_process.js:1011:16)
4216 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
4217 verbose pkgid mariasql@0.2.6
4218 verbose cwd /var/www/html/admin/modules/ucp/node
4219 verbose Linux 4.9.0-4-amd64
4220 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
4221 verbose node v12.2.0
4222 verbose npm  v6.9.0
4223 error code ELIFECYCLE
4224 error errno 1
4225 error mariasql@0.2.6 install: `node-gyp rebuild`
4225 error Exit status 1
4226 error Failed at the mariasql@0.2.6 install script.
4226 error This is probably not a problem with npm. There is likely additional logging output above.
4227 verbose exit [ 1, true ]

**Comment by wilibox** [comment]
One more thing I tried:
I ran upgrade tool from pbx 14 to 15 on the image I built 6 months ago and UCP daemon is running.
So I guess some tweaks still has to be done on the docker image.

**Comment by tiredofit** [comment]
I"ll try pushing a version with Node 11 - perhaps node 12 is the cause of this.
Also, sylhero who comments regularly in this repo has seen similar issues with UCP and ICU apparently there is a fix. I get the feeling the FreePBX developers are getting ready for new version of UCP, that would be welcome. I've had to move away from using FreePBX for my environment due to the UCP acting peculiar.
