### ISSUE TITLE
can not connect to asterisk

### ISSUE THREAD

**Issue by pepeshark** [tiredofit/docker-freepbx#84]
I started 2 docker instance with network_mode: "host".
The first one is working well. But the secound one is not.
When I try to restart with fconsole restart command I get an error message like this:
In php-asmanager.php line 495:
 fclose(): 112 is not a valid stream resource
And when I login to the admin interface I can see the following error message: "can not connect to asterisk"

In my opinion they try to bind same port.
But I changed the sip, pjsip ports.
Do you have any idea what port setting is wrong??
Thanks.

**Comment by pepeshark** [comment]
do you have any idea?

**Comment by pepeshark** [comment]
do you have any idea? I am still waiting for you answer or idea.

**Comment by tiredofit** [comment]
Two `network: host` perhaps? If they are trying to use the same ports there would be failures, but I would also think that it would not start with docker-copose. Could be wrong.

A good way to test is with your working installaiton and see what ports are being used: `netstat -tunap` And we can start to change those others.
