### ISSUE TITLE
User Control Panel (ucp) install error 

### ISSUE THREAD

**Issue by joltiy** [tiredofit/docker-freepbx#85]
Updating tables ucp_sessions...Завершено
icu is not installed. You need to run: yum install icu libicu-devel

### FIX:

In line 95 in **/var/www/html/admin/modules/ucp/Ucp.class.php** has

`$output = exec("icu-config --version");

Create file **/usr/bin/icu-config** with the of

`icuinfo 2>/dev/null|grep '"version"'|sed 's/.*">\(.*\)<.*/\1/g'`

and in **docker-compose.yml**
`volumes:`
 `    - /mnt/docker/fix/icu-config:/usr/bin/icu-config`

**Comment by junalmeida** [comment]
I've solved this manually installing libicu from the following: 
https://packages.debian.org/jessie/amd64/libicu52/download
