### ISSUE TITLE
installing the image on raspberry pi 3 b+

### ISSUE THREAD

**Issue by engrbm87** [tiredofit/docker-freepbx#87]
I am trying to install the docker image on my rpi 3b+ running raspbian stretch but it is giving this error in the logs:
``standard_init_linux.go:207: exec user process caused "exec format error"``
Can you let me know what needs to be modified for it to run.

**Comment by crazyquark** [comment]
That's because there are a lot of x86 binaries in there(not meant to be run on ARM). I tried too...

**Comment by tiredofit** [comment]
If I had access a rpi (I dont anymore) I'd be more than happy to start building an arm variant.

**Comment by crazyquark** [comment]
In theory you could do it on an Odroid, from one of the odroids provided for Hardkernel for testing:
https://forum.odroid.com/viewtopic.php?f=29&t=32257

**Comment by lights0123** [comment]
Docker can easily cross-compile images, see this [blog post](https://www.docker.com/blog/multi-platform-docker-builds/) or these commands:
```bash
docker run --privileged --rm docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
export DOCKER_CLI_EXPERIMENTAL=enabled
docker buildx build --platform linux/arm/v7 -t image-tag .
```

**Comment by crazyquark** [comment]
Indeed, I cross build my version too now. However, asterisk crashes in QEMU so tha last part, the install has be done on the ARM board, so I split the image in a base image and the final image:
https://github.com/crazyquark/freepbx-docker (a mix of this repo an another one, not a direct fork)
I diverged a bit from the original.
@engrbm87 give my version  a try, I also include chan_dongle built for ARM.
