### ISSUE TITLE
/var/spool/cron: No such file or directory

### ISSUE THREAD

**Issue by lucize** [tiredofit/docker-freepbx#94]
it seems that there is already a cron file in /var/spool/ so folder /var/spool/cron can't be created
issue seen on 15 and latest (at least)
first startup will endlessly loop for
```
/var/spool/cron: No such file or directory
/var/spool/cron: mkdir: File exists
/var/** [cron] Starting cron
/var/spool/cron: No such file or directory
/var/spool/cron: mkdir: File exists
spool/c** [cron] Starting cron
/var/spool/cron: No such file or directory
/var/spool/cron: mkdir: File exists
```

**Comment by tiredofit** [comment]
OK, there was some work before that was done to make cron jobs be accessible between container restarts (Freepbx was doing somerhing to it when hitting the apply button). In the meantime `ENABLE_CRON=FALSE` as an environment variable should get you up and running. I will look into in the next few hours.

**Comment by lucize** [comment]
I'm just starting to test this and /var/lib/mongodb (a file) and /var/log/mongodb/ (folder missing)
don't know if this matters as I'm using the default start and I'm learning to use it

**Comment by tiredofit** [comment]
OK - are you using my example docker-compose.yml ?
If not or if you've modified, care to share it here (strip the juicy bits of your hostname/db info)

**Comment by lucize** [comment]
I think that is the default
docker pull tiredofit/freepbx:15
and docker start image_name

**Comment by tiredofit** [comment]
Highly recommend you use the https://github.com/tiredofit/docker-freepbx/blob/15/examples/docker-compose.yml in the repo - there are a couple dozen environment variables in place, and if you follow that example you'll have a working system

**Comment by lucize** [comment]
sorry for the ignorance, I saw the example but where do I edit it (in /var/lib/docker/containers/ ? ), it will take new setting with the image already installed ?

**Comment by lucize** [comment]
I think docker-compose is the answer

**Comment by tiredofit** [comment]
Just drop the docker-compose.yml somewhere on your file system (i personally like /var/local/data/hostname.tld/docker-compose.yml but whatever you want), and execute `docker-compose up -d`
Watch the logs `docker-compose logs -f` and you should be in a good state.

**Comment by MSProgrammer** [comment]
Please Turn Off your Fire Wall , this is the Answer , 
it`s try to download Dependencies ,  so firewall banned port of docker container

**Comment by bbcbear** [comment]
Have the same problem.
I tried on two different docker installations but I get the same result.
Container build stuck on [INFO] ** [cron] Starting cron
Used stock docker-compose.yml from both repositories. =(

**Comment by tiredofit** [comment]
I understand what the problem is now. All of the services are seperated out and Cron (being run before the Asterisk script) and relies on this data manipulation to ensure persistent cron storage. 
I think I should be able to put forth an easy fix and post a develop image before comitting the actual and having it overwrite :latest. Let me look into this and try to have something by EOD

**Comment by tiredofit** [comment]
OK, switch to `tiredofit/freepbx:develop` temporarily and see if this resolves the issue.

**Comment by bbcbear** [comment]
> OK, switch to `tiredofit/freepbx:develop` temporarily and see if this resolves the issue.

I tried the developer's branch. The last message from the docker was about - [INFO] ** [cron] Starting cron
Maybe I'm dumb and is this normal behavior? =)
But after restarting the container, everything works.
Last time, the application container fell.

**Comment by tiredofit** [comment]
Sounds like it's working, and no you aren't dumb. It's a complex image and there's all sorts of information that is displayed to users of it that may or may not make sense.  I will merge this change to master in next day. Thanks for helping out test this.

**Comment by bbcbear** [comment]
> Sounds like it's working, and no you aren't dumb. It's a complex image and there's all sorts of information that is displayed to users of it that may or may not make sense. I will merge this change to master in next day. Thanks for helping out test thi

Thanks for the quick fix!
I would suggest that at the end of the deployment, something like "deployed successfully."
