### ISSUE TITLE
unable to build the image from Dockerfile

### ISSUE THREAD

**Issue by bendhb** [tiredofit/docker-freepbx#95]
The below error encountered when building image from the Dockerfile, it complains missing libxml2, however it is already included in ASTERISK_BUILD_DEPS:
..................
checking for xml2-config... no
configure: *** The Asterisk menuselect tool requires the 'libxml2' development package.
configure: *** Please install the 'libxml2' development package.
..................

**Comment by tiredofit** [comment]
I am seeing the same results - Something must have changed with the Debian XML package that Asterisk can no longer see it during the ./configure step. I'm at a loss right now on how to resolve. Debian's site doesn't tell when the version changed as far as I know.

**Comment by ivanfilippov** [comment]
The sury.org repo this image uses for PHP packages recently updated their version of libxml2-dev and this new version is what gets installed during the 'apt-get install' stage. This new version removed /usr/bin/xml2-config in favor of using pkg-config, but the Asterisk configure script isn't built to use it.

My quick and dirty fix for this was to add the below snippet into the Dockerfile immediately below the line that reads "### Install Dependencies". This forces apt-get to only install libxml2 and libxml2-dev from the official Debian repos. This allows the build process to complete successfully but I have not had a chance to make sure that no functionality was affected in other parts of this image.

```
RUN echo "Package: libxml2*" > /etc/apt/preferences.d/libxml2-dev && \
    echo "Pin: release o=Debian,n=stretch" >> /etc/apt/preferences.d/libxml2-dev && \
    echo "Pin-Priority: 501" >> /etc/apt/preferences.d/libxml2-dev
````

The final fix for this has to come from upstream Asterisk, as they have to update their configure script to detect libxml2-dev via pkg-config (see the references at the bottom).

While you can patch the Asterisk configure script in the same way as the second reference below as part of the Docker build process, I'd recommend waiting for upstream Asterisk to fix this when they get to it and use the package pinning snippet for now. I can submit a PR if you're on board with that.

This is the GitHub issue that tipped me off (note the developer mentions that the change was reverted 10 days ago, but I was still experiencing this issue today).
https://github.com/oerdnj/deb.sury.org/issues/1238

This last comment in the below issue links to a patch for the configure script for a PHP package, which is similar to what Asterisk would need to do to their script.
https://github.com/oerdnj/deb.sury.org/issues/1237

**Comment by tiredofit** [comment]
Nice sleuthing work. I'd love a PR to merge in!

**Comment by ivanfilippov** [comment]
PRs submitted. Both branch images build successfully after the changes (with slight modification of the 15 branch due to not being able to grab spandsp since www.soft-switch.org is down).
